# Generated by Django 5.0.1 on 2026-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('department_section_cell', models.CharField(blank=True, max_length=255, verbose_name='Department/Section/Cell')),
                ('roles', models.CharField(blank=True, help_text='Comma separated values indicating associated sections for roles', max_length=500)),
                ('dob', models.DateField(blank=True, null=True)),
                ('insti_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('other_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('staff_type', models.CharField(blank=True, help_text='e.g., Permanent, Contract', max_length=100)),
                ('campus', models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if the staff member leaves the university')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['name'],
            },
        ),
    ]
