# Generated by Django 5.0.1 on 2026-04-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
