# Generated by Django 5.0.1 on 2026-05-07 07:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_staff_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStaff',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('staff_no', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('department_section_cell', models.CharField(blank=True, max_length=255, verbose_name='Department/Section/Cell')),
                ('roles', models.CharField(blank=True, help_text='Comma separated values indicating associated sections for roles', max_length=500)),
                ('dob', models.DateField(blank=True, null=True)),
                ('insti_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('other_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('staff_type', models.CharField(blank=True, help_text='e.g., Permanent, Contract', max_length=100)),
                ('campus', models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if the staff member leaves the university')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical staff',
                'verbose_name_plural': 'historical Staff',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
