# Generated by Django 5.0.1 on 2026-09-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_historicalstaff_user_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstaff',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='roles',
        ),
    ]
