# Generated by Django 5.0.1 on 2026-04-08 10:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Detailed content of the notice', null=True)),
                ('category', models.CharField(choices=[('Announcement', 'Announcement'), ('Event', 'Event'), ('Appointment', 'Appointment'), ('Tenders', 'Tenders')], max_length=50)),
                ('link', models.URLField(blank=True, help_text='Optional external link or relative URL', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='global_notices/')),
                ('show_in_marquee', models.BooleanField(default=False, help_text='Show this notice in the scrolling marquee at the top of the homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
