# Generated by Django 5.0.1 on 2026-04-08 11:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalnotice',
            name='category',
        ),
        migrations.AddField(
            model_name='globalnotice',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Announcement', 'Announcement'), ('Event', 'Event'), ('Appointment', 'Appointment'), ('Tenders', 'Tenders')], max_length=50), blank=True, default=list, help_text='Select one or more categories', size=None),
        ),
    ]
