# Generated by Django 5.0.1 on 2026-04-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_globalnotice_category_globalnotice_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalnotice',
            name='content',
        ),
    ]
