# Generated by Django 5.0.1 on 2026-05-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_remove_globalnotice_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalnotice',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'Homepage Notices'},
        ),
    ]
