# Generated by Django 5.0.1 on 2026-05-06 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_alter_globalnotice_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnotice',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, this notice will only be visible to logged-in faculty/staff.'),
        ),
        migrations.AddField(
            model_name='globalnotice',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
