# Generated by Django 5.0.1 on 2026-05-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_globalnotice_is_private_globalnotice_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnotice',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical')], default='Normal', help_text='Set the importance level of this notice.', max_length=10),
        ),
    ]
