# Generated by Django 5.0.1 on 2026-05-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_globalnotice_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalnotice',
            name='priority',
        ),
    ]
