# Generated by Django 5.0.1 on 2026-05-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_remove_globalnotice_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalnotice',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'General Notices'},
        ),
    ]
