# Generated by Django 5.0.1 on 2026-05-07 07:09

import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_alter_globalnotice_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGlobalNotice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Announcement', 'Announcement'), ('Event', 'Event'), ('Appointment', 'Appointment'), ('Tenders', 'Tenders')], max_length=50), blank=True, default=list, help_text='Select one or more categories', size=None)),
                ('link', models.URLField(blank=True, help_text='Optional external link or relative URL', null=True)),
                ('attachment', models.TextField(blank=True, max_length=100, null=True)),
                ('show_in_marquee', models.BooleanField(default=False, help_text='Show this notice in the scrolling marquee at the top of the homepage')),
                ('is_private', models.BooleanField(default=False, help_text='If checked, this notice will only be visible to logged-in faculty/staff.')),
                ('is_active', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical global notice',
                'verbose_name_plural': 'historical General Notices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
