# Generated by Django 5.0.1 on 2026-05-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0009_historicalglobalnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnotice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalnotice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalglobalnotice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalglobalnotice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
