# Generated by Django 5.0.1 on 2026-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0010_globalnotice_deleted_at_globalnotice_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalnotice',
            name='date_posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalglobalnotice',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
