# Generated by Django 5.0.1 on 2026-07-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0011_alter_globalnotice_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnotice',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='The date after which this notice automatically becomes archived.', null=True),
        ),
        migrations.AddField(
            model_name='globalnotice',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive this notice immediately.'),
        ),
        migrations.AddField(
            model_name='historicalglobalnotice',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='The date after which this notice automatically becomes archived.', null=True),
        ),
        migrations.AddField(
            model_name='historicalglobalnotice',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive this notice immediately.'),
        ),
        migrations.AlterField(
            model_name='globalnotice',
            name='date_posted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalglobalnotice',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
