# Generated by Django 5.0.1 on 2026-07-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0012_globalnotice_expiry_date_globalnotice_is_archived_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalnotice',
            old_name='expiry_date',
            new_name='archive_date',
        ),
        migrations.RenameField(
            model_name='historicalglobalnotice',
            old_name='expiry_date',
            new_name='archive_date',
        ),
    ]
