# Generated by Django 5.0.1 on 2026-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0013_rename_expiry_date_globalnotice_archive_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnotice',
            name='internal_link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalglobalnotice',
            name='internal_link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalnotice',
            name='link',
            field=models.URLField(blank=True, help_text='Optional external link or relative URL', null=True, verbose_name='External Link'),
        ),
        migrations.AlterField(
            model_name='historicalglobalnotice',
            name='link',
            field=models.URLField(blank=True, help_text='Optional external link or relative URL', null=True, verbose_name='External Link'),
        ),
    ]
