# Generated by Django 5.0.1 on 2026-09-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0015_globalnotice_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalnotice',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching'), ('Resourse Person', 'Resourse Person'), ('Others', 'Others')], default='TE', max_length=50, verbose_name='Appointment Choice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalglobalnotice',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching'), ('Resourse Person', 'Resourse Person'), ('Others', 'Others')], default='TEACHING', max_length=50, verbose_name='Appointment Choice'),
            preserve_default=False,
        ),
    ]
