# Generated by Django 5.0.1 on 2026-09-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0016_alter_globalnotice_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalnotice',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching'), ('Resource Person', 'Resource Person'), ('Others', 'Others')], max_length=50, verbose_name='Appointment Choice'),
        ),
        migrations.AlterField(
            model_name='historicalglobalnotice',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching'), ('Resource Person', 'Resource Person'), ('Others', 'Others')], max_length=50, verbose_name='Appointment Choice'),
        ),
    ]
