# Generated by Django 5.0.1 on 2026-04-26 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('HOD', 'Head of Department'), ('DEPT_STAFF', 'Department Staff'), ('RD_ADMIN', 'R&D Cell Admin'), ('HOSTEL_WARDEN', 'Hostel Warden'), ('BOARD_MEMBER', 'Board Member'), ('FACULTY', 'Faculty')], help_text='The role this user holds within the entity.', max_length=30)),
                ('entity_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('RD_CELL', 'R&D Cell'), ('HOSTEL', 'Hostel'), ('BOARD', 'Board'), ('UNIVERSITY', 'University')], help_text='The type of entity this access is scoped to.', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to revoke access without deleting the record.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('granted_by', models.ForeignKey(blank=True, help_text='The user (Superadmin or HOD) who granted this access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal Access',
                'verbose_name_plural': 'Portal Access Entries',
                'ordering': ['entity_type', 'role'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='University employee/staff ID', max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='portal_users/')),
                ('is_portal_user', models.BooleanField(default=False, help_text='Designates whether this user has access to the ERP portal.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddConstraint(
            model_name='portalaccess',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'content_type', 'object_id'), name='unique_user_role_entity'),
        ),
    ]
