# Generated by Django 5.0.1 on 2026-04-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalaccess',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('HOD', 'Head of Department'), ('DEPT_STAFF', 'Department Staff'), ('RD_ADMIN', 'R&D Cell Admin'), ('FACULTY', 'Faculty'), ('HOSTEL_WARDEN', 'Hostel Warden'), ('BOARD_MEMBER', 'Board Member')], help_text='The role this user holds within the entity.', max_length=30),
        ),
    ]
