# Generated by Django 5.0.1 on 2026-04-27 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_portalaccess_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalaccess',
            options={'verbose_name_plural': 'Portal Access Entries'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='portalaccess',
            name='unique_user_role_entity',
        ),
        migrations.RemoveField(
            model_name='portalaccess',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='portalaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='portalaccess',
            name='entity_type',
            field=models.CharField(choices=[('DEPARTMENT', 'Department'), ('SCHOOL', 'School'), ('CENTRE', 'Centre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='portalaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portalaccess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='portalaccess',
            name='role',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('DEPT_STAFF', 'Department Staff'), ('RD_ADMIN', 'R&D Cell Admin'), ('FACULTY', 'Faculty Member')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_portal_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='portal/profiles/'),
        ),
    ]
