# Generated by Django 5.0.1 on 2026-04-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_portalaccess_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='If True, the user will be forced to change their password on next login.'),
        ),
    ]
