# Generated by Django 5.0.1 on 2026-04-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_portalaccess_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(help_text='If True, the user will be forced to change their password on next login.'),
        ),
    ]
