# Generated by Django 5.0.1 on 2026-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_force_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='If True, the user will be forced to change their password on next login.'),
        ),
    ]
