# Generated by Django 5.0.1 on 2026-05-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_force_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalaccess',
            name='role',
            field=models.CharField(choices=[('DEAN', 'Dean / Director'), ('HOD', 'HOD / Coordinator'), ('DEPT_STAFF', 'Department Staff'), ('RD_ADMIN', 'R&D Cell Admin'), ('FACULTY', 'Faculty Member')], max_length=50),
        ),
    ]
