# Generated by Django 5.0.1 on 2026-05-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_portalaccess_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalaccess',
            name='role',
            field=models.CharField(choices=[('DEAN', 'Dean / Director'), ('HOD', 'HOD / Coordinator'), ('DEPT_STAFF', 'Department Staff'), ('RD_ADMIN', 'R&D Cell Admin'), ('FACULTY', 'Faculty Member'), ('REGISTRAR', 'Registrar Office'), ('FINANCE_SECTION', 'Finance Section'), ('ACADEMIC_SECTION', 'Academic Section')], max_length=50),
        ),
    ]
