# Generated by Django 5.0.1 on 2026-07-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_globaltrashitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globaltrashitem',
            options={'ordering': ['-deleted_at'], 'verbose_name': 'Global Trash Item', 'verbose_name_plural': '(Recycle Bin)'},
        ),
    ]
