version: '3.8'

services:
  django-stag:
    build: .
    container_name: django-stag
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8002:8000"
    env_file:
      - .env.stag
    depends_on:
      - postgres
    networks:
      - college-network
    restart: unless-stopped

networks:
  college-network:
    external: true
