version: "3.8"

services:
  django-stag:
    build: .
    container_name: django-stag
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8002:8000"
    env_file:
      - .env.stag
    networks:
      - college-network
    restart: unless-stopped

networks:
  college-network:
    external: true
