# Generated by Django 5.0.1 on 2026-07-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notices', '0012_globalnotice_expiry_date_globalnotice_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedGlobalNotice',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Notice',
                'verbose_name_plural': 'Archived Notices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notices.globalnotice',),
        ),
    ]
