# Generated by Django 5.0.1 on 2026-07-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
        ('mou', '0007_historicalmou_is_archived_mou_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedMOU',
            fields=[
            ],
            options={
                'verbose_name': 'Archived MOU',
                'verbose_name_plural': 'Archived MOUs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mou.mou',),
        ),
    ]
