# Generated by Django 5.0.1 on 2026-07-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_admissioncommitteeminutes_archive_date_and_more'),
        ('archives', '0002_archivedmou'),
        ('authorities', '0007_academiccouncilminutes_archive_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedAcademicCouncilMinutes',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Academic Council Minutes',
                'verbose_name_plural': 'Archived Academic Council Minutes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authorities.academiccouncilminutes',),
        ),
        migrations.CreateModel(
            name='ArchivedAdmissionCommitteeMinutes',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Admission Committee Minutes',
                'verbose_name_plural': 'Archived Admission Committee Minutes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admission.admissioncommitteeminutes',),
        ),
        migrations.CreateModel(
            name='ArchivedAdmissionNotice',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Admission Notice',
                'verbose_name_plural': 'Archived Admission Notices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admission.admissionnotice',),
        ),
        migrations.CreateModel(
            name='ArchivedBoardOfManagementMinutes',
            fields=[
            ],
            options={
                'verbose_name': 'Archived BoM Minutes',
                'verbose_name_plural': 'Archived BoM Minutes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authorities.boardofmanagementminutes',),
        ),
        migrations.CreateModel(
            name='ArchivedFinanceCommitteeMinutes',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Finance Committee Minutes',
                'verbose_name_plural': 'Archived Finance Committee Minutes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authorities.financecommitteeminutes',),
        ),
        migrations.CreateModel(
            name='ArchivedPlanningBoardMinutes',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Planning Board Minutes',
                'verbose_name_plural': 'Archived Planning Board Minutes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authorities.planningboardminutes',),
        ),
    ]
