# Generated by Django 5.0.1 on 2026-08-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_archivedacademiccouncilminutes_and_more'),
        ('coe', '0001_initial'),
        ('proctor', '0004_remove_historicalproctorialboardmember_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedCOENotice',
            fields=[
            ],
            options={
                'verbose_name': 'Archived COE Notice',
                'verbose_name_plural': 'Archived COE Notices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coe.coenotice',),
        ),
        migrations.CreateModel(
            name='ArchivedMPHILVivaVoceDate',
            fields=[
            ],
            options={
                'verbose_name': 'Archived MPHIL Viva Voce Date',
                'verbose_name_plural': 'Archived MPHIL Viva Voce Dates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coe.mphilvivavocedate',),
        ),
        migrations.CreateModel(
            name='ArchivedPHDPreSubmissionSeminar',
            fields=[
            ],
            options={
                'verbose_name': 'Archived PHD Pre Submission Seminar',
                'verbose_name_plural': 'Archived PHD Pre Submission Seminars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coe.phdpresubmissionseminar',),
        ),
        migrations.CreateModel(
            name='ArchivedPHDVivaVoceDate',
            fields=[
            ],
            options={
                'verbose_name': 'Archived PHD Viva Voce Date',
                'verbose_name_plural': 'Archived PHD Viva Voce Dates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coe.phdvivavocedate',),
        ),
        migrations.CreateModel(
            name='ArchivedProctorialBoardMinutes',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Proctorial Board Minutes',
                'verbose_name_plural': 'Archived Proctorial Board Minutes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proctor.proctorialboardminutes',),
        ),
        migrations.CreateModel(
            name='ArchivedProctorialBoardNotice',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Proctorial Board Notice',
                'verbose_name_plural': 'Archived Proctorial Board Notices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proctor.proctorialboardnotice',),
        ),
        migrations.CreateModel(
            name='ArchivedRDCUNotice',
            fields=[
            ],
            options={
                'verbose_name': 'Archived RDCU Notice',
                'verbose_name_plural': 'Archived RDCU Notices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coe.rdcunotice',),
        ),
    ]
