# Generated by Django 5.0.1 on 2026-03-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='dean_employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='dean_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
