# Generated by Django 5.0.1 on 2026-03-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_school_dean_employee_id_alter_school_dean_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schools/'),
        ),
    ]
