# Generated by Django 5.0.1 on 2026-03-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_department_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='dean_employee_id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='dean_name',
        ),
    ]
