# Generated by Django 5.0.1 on 2026-03-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_school_dean_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='about_school',
            field=models.TextField(blank=True),
        ),
    ]
