# Generated by Django 5.0.1 on 2026-03-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_department_centre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='centre',
        ),
    ]
