# Generated by Django 5.0.1 on 2026-03-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_department_centre'),
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='centres.centre'),
        ),
    ]
