# Generated by Django 5.0.1 on 2026-04-02 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_department_about_department_contact_email_and_more'),
        ('faculty', '0005_remove_faculty_one_dean_per_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_of_departments', to='faculty.faculty'),
        ),
    ]
