# Generated by Django 5.0.1 on 2026-04-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_department_hod'),
        ('faculty', '0005_remove_faculty_one_dean_per_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_of_schools', to='faculty.faculty'),
        ),
    ]
