# Generated by Django 5.0.1 on 2026-04-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_school_dean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='department',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='school',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='school',
            name='vision',
        ),
        migrations.AddField(
            model_name='committeemember',
            name='other_designation',
            field=models.CharField(blank=True, help_text="Please specify the designation if 'Others' is selected", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='other_level',
            field=models.CharField(blank=True, help_text="Please specify the level if 'Others' is selected", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='designation_in_committee',
            field=models.CharField(choices=[('Chairperson', 'Chairperson'), ('Member', 'Member'), ('Member & Convener', 'Member & Convener'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'PhD'), ('Others', 'Others')], max_length=50),
        ),
    ]
