# Generated by Django 5.0.1 on 2026-04-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_remove_department_mission_remove_department_vision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='duration_years',
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 4 Years, 6 Semesters', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='eligibility',
            field=models.TextField(blank=True, help_text='Eligibility criteria for the program', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='fees',
            field=models.CharField(blank=True, help_text='Fee structure details', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='intake',
            field=models.PositiveIntegerField(blank=True, help_text='Number of seats available', null=True),
        ),
    ]
