# Generated by Django 5.0.1 on 2026-04-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_remove_program_duration_years_program_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='intake',
            field=models.CharField(blank=True, help_text='Number of seats available', max_length=100, null=True),
        ),
    ]
