# Generated by Django 5.0.1 on 2026-04-06 08:07

import apps.academics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_program_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.academics.models.department_gallery_upload_path)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='academics.department')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
