# Generated by Django 5.0.1 on 2026-04-06 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_departmentgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cbcs_details',
            field=models.TextField(blank=True, help_text='Choice Based Credit System details', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_outcomes',
            field=models.TextField(blank=True, help_text='Detailed program outcomes/objectives', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='syllabus',
            field=models.FileField(blank=True, help_text='Downloadable syllabus document', null=True, upload_to='programs/syllabus/'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(help_text='e.g., 1, 2, 3...')),
                ('course_code', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField()),
                ('course_type', models.CharField(choices=[('Core', 'Core'), ('Elective', 'Elective'), ('Practical', 'Practical'), ('Project', 'Project'), ('Seminar', 'Seminar'), ('Others', 'Others')], default='Core', max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.program')),
            ],
            options={
                'ordering': ['semester', 'course_code'],
            },
        ),
    ]
