# Generated by Django 5.0.1 on 2026-04-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_program_cbcs_details_program_program_outcomes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='cbcs_details',
        ),
        migrations.AddField(
            model_name='course',
            name='other_course_type',
            field=models.CharField(blank=True, help_text="Please specify if course type is 'Others'", max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CBCSCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(help_text='e.g., 1, 2, 3...')),
                ('course_code', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbcs_courses', to='academics.program')),
            ],
            options={
                'ordering': ['semester', 'course_code'],
            },
        ),
    ]
