# Generated by Django 5.0.1 on 2026-04-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_remove_program_cbcs_details_course_other_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Core', 'Core'), ('Elective', 'Elective'), ('Practical', 'Practical'), ('Others', 'Others')], default='Core', max_length=50),
        ),
    ]
