# Generated by Django 5.0.1 on 2026-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_alter_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='dean_message',
            field=models.TextField(blank=True),
        ),
    ]
