# Generated by Django 5.0.1 on 2026-04-06 12:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_school_dean_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='thrust_areas',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Major research and academic focus areas of the department'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='eligibility',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Eligibility criteria for the program', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_outcomes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed program outcomes/objectives', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='about_school',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='dean_message',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
