# Generated by Django 5.0.1 on 2026-04-06 18:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_alter_committee_description_alter_department_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='admission_process',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Admission process for the program', null=True),
        ),
    ]
