# Generated by Django 5.0.1 on 2026-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_program_admission_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Core', 'Core'), ('Elective', 'Elective'), ('Compulsory Elective', 'Compulsory Elective'), ('Compulsory Foundation', 'Compulsory Foundation'), ('Practical', 'Practical'), ('Others', 'Others')], default='Core', max_length=50),
        ),
    ]
