# Generated by Django 5.0.1 on 2026-04-08 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_alter_course_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbcscourse',
            name='program',
        ),
        migrations.AddField(
            model_name='cbcscourse',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbcs_courses', to='academics.department'),
        ),
    ]
