# Generated by Django 5.0.1 on 2026-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_remove_cbcscourse_program_cbcscourse_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Academic', 'Academic'), ('Examination', 'Examination'), ('Admission', 'Admission'), ('Scholarship', 'Scholarship'), ('Others', 'Others')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='notice',
            name='other_category',
            field=models.CharField(blank=True, help_text="Specify if 'Others' selected", max_length=100, null=True),
        ),
    ]
