# Generated by Django 5.0.1 on 2026-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_notice_category_notice_other_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Academic', 'Academic'), ('Examination', 'Examination'), ('Admission', 'Admission'), ('Scholarship', 'Scholarship'), ('Others', 'Others')], max_length=50),
        ),
    ]
