# Generated by Django 5.0.1 on 2026-04-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_alter_notice_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchscholar',
            name='co_supervisor',
        ),
        migrations.RemoveField(
            model_name='researchscholar',
            name='department',
        ),
        migrations.RemoveField(
            model_name='researchscholar',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='ResearchProject',
        ),
        migrations.DeleteModel(
            name='ResearchScholar',
        ),
    ]
