# Generated by Django 5.0.1 on 2026-04-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0031_alter_department_school'),
        ('faculty', '0020_alter_faculty_bio_alter_faculty_google_scholar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='academics.committee'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.program'),
        ),
        migrations.AlterField(
            model_name='departmentgallery',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.department'),
        ),
    ]
