# Generated by Django 5.0.1 on 2026-04-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0032_alter_committee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50),
        ),
    ]
