# Generated by Django 5.0.1 on 2026-04-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_department_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('Core', 'Core'), ('Elective', 'Elective'), ('Compulsory Elective', 'Compulsory Elective'), ('Compulsory Foundation', 'Compulsory Foundation'), ('Practical', 'Practical'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveIntegerField(blank=True, help_text='e.g., 1, 2, 3...', null=True),
        ),
    ]
