# Generated by Django 5.0.1 on 2026-04-29 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0034_alter_course_course_type_alter_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbcscourse',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbcs_courses', to='academics.program'),
        ),
    ]
