# Generated by Django 5.0.1 on 2026-04-30 11:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0036_historicaldepartment_historicalschool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', 'course_code'], 'verbose_name_plural': 'Course structure'},
        ),
        migrations.AddField(
            model_name='program',
            name='notification_or_document_file',
            field=models.FileField(blank=True, help_text='Downloadable document related to the program', null=True, upload_to='programs/documents/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='fees',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Fee structure details', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('Integrated', 'Integrated'), ('PHD', 'PhD'), ('Others', 'Others')], max_length=50),
        ),
    ]
