# Generated by Django 5.0.1 on 2026-04-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0037_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='notification_document',
            field=models.FileField(blank=True, null=True, upload_to='committees/notification/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=50, verbose_name='Course/ Paper Code'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of Program'),
        ),
    ]
