# Generated by Django 5.0.1 on 2026-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0038_committee_notification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='name_of_member',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Committee Member'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='notification_document',
            field=models.FileField(blank=True, help_text='Notification or document related to the committee', null=True, upload_to='committees/notification/'),
        ),
    ]
