# Generated by Django 5.0.1 on 2026-04-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0039_committeemember_name_of_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='faculty',
        ),
    ]
