# Generated by Django 5.0.1 on 2026-04-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0040_remove_committeemember_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutesOfTheMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_meeting', models.DateField(auto_now_add=True)),
                ('minutes_of_meeting', models.FileField(blank=True, help_text='Minutes of the meeting', null=True, upload_to='committees/minutes/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='academics.department')),
            ],
        ),
    ]
