# Generated by Django 5.0.1 on 2026-04-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0041_minutesofthemeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutesofthemeeting',
            name='date_of_meeting',
            field=models.DateField(help_text='Enter date of meeting in YYYY-MM-DD format'),
        ),
        migrations.AlterField(
            model_name='minutesofthemeeting',
            name='minutes_of_meeting',
            field=models.FileField(blank=True, help_text='Upload Minutes of the meeting', null=True, upload_to='committees/minutes/'),
        ),
    ]
