# Generated by Django 5.0.1 on 2026-04-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0042_alter_minutesofthemeeting_date_of_meeting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutesofthemeeting',
            options={'ordering': ['-date_of_meeting'], 'verbose_name_plural': 'Minutes (MOM)'},
        ),
    ]
