# Generated by Django 5.0.1 on 2026-04-30 22:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0043_alter_minutesofthemeeting_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSchoolBoardCommittee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('members', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Member', 'Member'), ('Member & Convener', 'Member & Convener'), ('Others', 'Others')], default='Member', max_length=255)),
                ('other_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_or_document', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.school')),
            ],
            options={
                'verbose_name': 'historical school board committee',
                'verbose_name_plural': 'historical School Board Committees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSchoolBoardMOM',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_of_meeting', models.DateField(help_text='Date of the Meeting in yyyy-mm-dd format')),
                ('minutes', models.TextField(help_text='Upload Minutes of the Meeting', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.school')),
            ],
            options={
                'verbose_name': 'historical school board mom',
                'verbose_name_plural': 'historical School Board Minutes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SchoolBoardCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Member', 'Member'), ('Member & Convener', 'Member & Convener'), ('Others', 'Others')], default='Member', max_length=255)),
                ('other_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_or_document', models.FileField(upload_to='schools/board-committee-documents/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_board_committee', to='academics.school')),
            ],
            options={
                'verbose_name_plural': 'School Board Committees',
            },
        ),
        migrations.CreateModel(
            name='SchoolBoardMOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_meeting', models.DateField(help_text='Date of the Meeting in yyyy-mm-dd format')),
                ('minutes', models.FileField(help_text='Upload Minutes of the Meeting', upload_to='schools/school-board-mom/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_board_mom', to='academics.school')),
            ],
            options={
                'verbose_name_plural': 'School Board Minutes',
                'ordering': ['-date_of_meeting'],
            },
        ),
    ]
