# Generated by Django 5.0.1 on 2026-04-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0044_historicalschoolboardcommittee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschoolboardcommittee',
            name='designation',
            field=models.CharField(choices=[('Chairperson', 'Chairperson'), ('Member', 'Member'), ('Member & Convener', 'Member & Convener'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolboardcommittee',
            name='designation',
            field=models.CharField(choices=[('Chairperson', 'Chairperson'), ('Member', 'Member'), ('Member & Convener', 'Member & Convener'), ('Others', 'Others')], max_length=255),
        ),
    ]
