# Generated by Django 5.0.1 on 2026-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0045_alter_historicalschoolboardcommittee_designation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', 'position', 'course_code'], 'verbose_name_plural': 'Course structure'},
        ),
        migrations.AddField(
            model_name='course',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Order of the course'),
        ),
    ]
