# Generated by Django 5.0.1 on 2026-05-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0046_alter_course_options_course_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', 'course_code'], 'verbose_name_plural': 'Course structure'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='position',
        ),
    ]
