# Generated by Django 5.0.1 on 2026-05-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0047_alter_course_options_remove_course_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutesofthemeeting',
            options={'ordering': ['-date_of_meeting'], 'verbose_name_plural': 'Departmental Minutes '},
        ),
        migrations.AddField(
            model_name='minutesofthemeeting',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the meeting', max_length=255, null=True),
        ),
    ]
