# Generated by Django 5.0.1 on 2026-05-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0048_alter_minutesofthemeeting_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutesofthemeeting',
            old_name='title',
            new_name='meeting_title',
        ),
    ]
