# Generated by Django 5.0.1 on 2026-05-04 21:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0049_rename_title_minutesofthemeeting_meeting_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalSchoolBoardCommittee',
            new_name='HistoricalSchoolBoardCommitteeMember',
        ),
        migrations.RenameModel(
            old_name='SchoolBoardCommittee',
            new_name='SchoolBoardCommitteeMember',
        ),
        migrations.AlterModelOptions(
            name='historicalschoolboardcommitteemember',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical school board committee member', 'verbose_name_plural': 'historical School Board Committees'},
        ),
    ]
