# Generated by Django 5.0.1 on 2026-05-04 21:20

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0050_rename_historicalschoolboardcommittee_historicalschoolboardcommitteemember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalschoolboardcommitteemember',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical school board committee member', 'verbose_name_plural': 'historical School Board Committee Members'},
        ),
        migrations.AlterModelOptions(
            name='schoolboardcommitteemember',
            options={'verbose_name_plural': 'School Board Committee Members'},
        ),
        migrations.RemoveField(
            model_name='historicalschoolboardcommitteemember',
            name='notification_or_document',
        ),
        migrations.RemoveField(
            model_name='historicalschoolboardcommitteemember',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schoolboardcommitteemember',
            name='notification_or_document',
        ),
        migrations.RemoveField(
            model_name='schoolboardcommitteemember',
            name='school',
        ),
        migrations.CreateModel(
            name='HistoricalSchoolBoardCommittee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=255, null=True)),
                ('notification_or_document', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.school')),
            ],
            options={
                'verbose_name': 'historical school board committee',
                'verbose_name_plural': 'historical School Board Committee',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SchoolBoardCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=255, null=True)),
                ('notification_or_document', models.FileField(blank=True, null=True, upload_to='schools/board-committee-documents/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_board_committee', to='academics.school')),
            ],
            options={
                'verbose_name_plural': 'School Board Committee',
            },
        ),
        migrations.AddField(
            model_name='historicalschoolboardcommitteemember',
            name='committee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.schoolboardcommittee'),
        ),
        migrations.AddField(
            model_name='schoolboardcommitteemember',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_board_committee_members', to='academics.schoolboardcommittee'),
        ),
    ]
