# Generated by Django 5.0.1 on 2026-05-04 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0052_historicalcbcscourse_historicalcommittee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolboardcommitteemember',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='academics.schoolboardcommittee'),
        ),
    ]
