# Generated by Django 5.0.1 on 2026-05-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0053_alter_schoolboardcommitteemember_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschoolboardmom',
            name='meeting_title',
            field=models.CharField(blank=True, help_text='Title of the Meeting', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolboardmom',
            name='meeting_title',
            field=models.CharField(blank=True, help_text='Title of the Meeting', max_length=255, null=True),
        ),
    ]
