# Generated by Django 5.0.1 on 2026-05-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0054_historicalschoolboardmom_meeting_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschoolboardmom',
            name='minutes',
            field=models.TextField(blank=True, help_text='Upload Minutes of the Meeting', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schoolboardmom',
            name='minutes',
            field=models.FileField(blank=True, help_text='Upload Minutes of the Meeting', null=True, upload_to='schools/school-board-mom/'),
        ),
    ]
