# Generated by Django 5.0.1 on 2026-05-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0055_alter_historicalschoolboardmom_minutes_and_more'),
        ('faculty', '0025_historicalfaculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='leadership_title',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Coordinator', 'Coordinator')], default='HOD', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='leadership_title',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Coordinator', 'Coordinator')], default='HOD', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalschool',
            name='leadership_title',
            field=models.CharField(choices=[('Dean', 'Dean'), ('Director', 'Director')], default='Dean', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='leadership_title',
            field=models.CharField(choices=[('Dean', 'Dean'), ('Director', 'Director')], default='Dean', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_of_departments', to='faculty.faculty', verbose_name='Leadership'),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='hod',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faculty.faculty', verbose_name='Leadership'),
        ),
        migrations.AlterField(
            model_name='historicalschool',
            name='dean',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faculty.faculty', verbose_name='Leadership'),
        ),
        migrations.AlterField(
            model_name='school',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_of_schools', to='faculty.faculty', verbose_name='Leadership'),
        ),
    ]
