# Generated by Django 5.0.1 on 2026-05-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0057_cbcscourse_deleted_at_cbcscourse_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschool',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
