# Generated by Django 5.0.1 on 2026-05-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0058_alter_historicalschool_name_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschool',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
