# Generated by Django 5.0.1 on 2026-05-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0059_alter_historicalschool_name_alter_school_name'),
        ('centres', '0008_centre_about_centre_thrust_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbcscourse',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbcs_courses', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='committee',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='historicalcbcscourse',
            name='centre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='historicalcommittee',
            name='centre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='historicalminutesofthemeeting',
            name='centre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='historicalnotice',
            name='centre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='centre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='historicalstudymaterial',
            name='centre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='historicaltimetable',
            name='centre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='minutesofthemeeting',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='notice',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='program',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='centres.centre'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='centres.centre'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='academics.department'),
        ),
    ]
