# Generated by Django 5.0.1 on 2026-05-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0060_cbcscourse_centre_committee_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=100, verbose_name='Course/ Paper Code'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='course_code',
            field=models.CharField(max_length=100, verbose_name='Course/ Paper Code'),
        ),
    ]
