# Generated by Django 5.0.1 on 2026-06-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_alter_course_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentgallery',
            name='event_name',
            field=models.CharField(blank=True, help_text='Name of the event this image belongs to', max_length=255, null=True),
        ),
    ]
