# Generated by Django 5.0.1 on 2026-07-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0063_remove_departmentgallery_event_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentgalleryevent',
            options={'ordering': ['-date_of_event', '-created_at'], 'verbose_name_plural': 'Department Event Gallery'},
        ),
        migrations.AlterModelOptions(
            name='historicaldepartmentgalleryevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical department gallery event', 'verbose_name_plural': 'historical Department Event Gallery'},
        ),
    ]
