# Generated by Django 5.0.1 on 2026-07-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0064_alter_departmentgalleryevent_options_and_more'),
        ('centres', '0008_centre_about_centre_thrust_areas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'verbose_name_plural': 'Departmental Committees'},
        ),
        migrations.AlterModelOptions(
            name='committeemember',
            options={'verbose_name_plural': 'Departmental Committee Members'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommittee',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical committee', 'verbose_name_plural': 'historical Departmental Committees'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommitteemember',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical committee member', 'verbose_name_plural': 'historical Departmental Committee Members'},
        ),
        migrations.AlterField(
            model_name='department',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalschool',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='cbcscourse',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False), ('is_deleted', False)), fields=('department', 'course_code'), name='unique_cbcscourse_dept_code'),
        ),
        migrations.AddConstraint(
            model_name='cbcscourse',
            constraint=models.UniqueConstraint(condition=models.Q(('centre__isnull', False), ('is_deleted', False)), fields=('centre', 'course_code'), name='unique_cbcscourse_centre_code'),
        ),
    ]
