# Generated by Django 5.0.1 on 2026-07-07 06:42

from django.db import migrations, models


def resolve_duplicate_courses(apps, schema_editor):
    CBCSCourse = apps.get_model('academics', 'CBCSCourse')
    from django.db.models import Count

    # Resolve department duplicates
    dept_duplicates = (
        CBCSCourse.objects.filter(is_deleted=False, department__isnull=False)
        .values('department', 'course_code')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    for dup in dept_duplicates:
        courses = list(CBCSCourse.objects.filter(
            is_deleted=False,
            department_id=dup['department'],
            course_code=dup['course_code']
        ).order_by('-id'))
        # Keep the first one (latest), mark the rest as deleted
        for extra_course in courses[1:]:
            extra_course.is_deleted = True
            extra_course.save()

    # Resolve centre duplicates
    centre_duplicates = (
        CBCSCourse.objects.filter(is_deleted=False, centre__isnull=False)
        .values('centre', 'course_code')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    for dup in centre_duplicates:
        courses = list(CBCSCourse.objects.filter(
            is_deleted=False,
            centre_id=dup['centre'],
            course_code=dup['course_code']
        ).order_by('-id'))
        # Keep the first one (latest), mark the rest as deleted
        for extra_course in courses[1:]:
            extra_course.is_deleted = True
            extra_course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0064_alter_departmentgalleryevent_options_and_more'),
        ('centres', '0008_centre_about_centre_thrust_areas_and_more'),
    ]

    operations = [
        migrations.RunPython(resolve_duplicate_courses, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='committee',
            options={'verbose_name_plural': 'Departmental Committees'},
        ),
        migrations.AlterModelOptions(
            name='committeemember',
            options={'verbose_name_plural': 'Departmental Committee Members'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommittee',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical committee', 'verbose_name_plural': 'historical Departmental Committees'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommitteemember',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical committee member', 'verbose_name_plural': 'historical Departmental Committee Members'},
        ),
        migrations.AlterField(
            model_name='department',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalschool',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='cbcscourse',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False), ('is_deleted', False)), fields=('department', 'course_code'), name='unique_cbcscourse_dept_code'),
        ),
        migrations.AddConstraint(
            model_name='cbcscourse',
            constraint=models.UniqueConstraint(condition=models.Q(('centre__isnull', False), ('is_deleted', False)), fields=('centre', 'course_code'), name='unique_cbcscourse_centre_code'),
        ),
    ]
