# Generated by Django 5.0.1 on 2026-07-09 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0065_add_constraints_and_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentgallery',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='departmentgalleryevent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_events', to='academics.department'),
        ),
    ]
