# Generated by Django 5.0.1 on 2026-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0066_alter_departmentgallery_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbcscourse',
            name='syllabus',
            field=models.FileField(blank=True, help_text='Downloadable syllabus document', null=True, upload_to='cbcs_courses/syllabus/'),
        ),
        migrations.AddField(
            model_name='historicalcbcscourse',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Downloadable syllabus document', max_length=100, null=True),
        ),
    ]
