# Generated by Django 5.0.1 on 2026-07-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0067_cbcscourse_syllabus_historicalcbcscourse_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalcommittee',
            name='description',
        ),
        migrations.AddField(
            model_name='committee',
            name='other_name_of_committee',
            field=models.CharField(blank=True, help_text="Specify if 'Others' selected", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommittee',
            name='other_name_of_committee',
            field=models.CharField(blank=True, help_text="Specify if 'Others' selected", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(choices=[('DRC', 'Departmental Research Committee'), ('BPGS', 'Board of Post Graduate Studies'), ('BUGS', 'Board of Under Graduate Studies'), ('DPC', 'Departmental Purchase Committee'), ('Others', 'Others')], max_length=255, verbose_name='Name of Committee'),
        ),
        migrations.AlterField(
            model_name='historicalcommittee',
            name='name',
            field=models.CharField(choices=[('DRC', 'Departmental Research Committee'), ('BPGS', 'Board of Post Graduate Studies'), ('BUGS', 'Board of Under Graduate Studies'), ('DPC', 'Departmental Purchase Committee'), ('Others', 'Others')], max_length=255, verbose_name='Name of Committee'),
        ),
    ]
