# Generated by Django 5.0.1 on 2026-07-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0068_remove_committee_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='other_name_of_committee',
            new_name='other_name',
        ),
        migrations.RenameField(
            model_name='historicalcommittee',
            old_name='other_name_of_committee',
            new_name='other_name',
        ),
    ]
