# Generated by Django 5.0.1 on 2026-07-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0069_rename_other_name_of_committee_committee_other_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalminutesofthemeeting',
            name='committee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.committee'),
        ),
        migrations.AddField(
            model_name='minutesofthemeeting',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='academics.committee'),
        ),
    ]
