# Generated by Django 5.0.1 on 2026-07-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0070_historicalminutesofthemeeting_committee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalminutesofthemeeting',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='historicalminutesofthemeeting',
            name='department',
        ),
        migrations.RemoveField(
            model_name='minutesofthemeeting',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='minutesofthemeeting',
            name='department',
        ),
        migrations.AddField(
            model_name='historicalminutesofthemeeting',
            name='meeting_number',
            field=models.IntegerField(blank=True, help_text='Enter the meeting number. Eg: 1st, 2nd, 3rd, etc.', null=True, verbose_name='Meeting Number'),
        ),
        migrations.AddField(
            model_name='minutesofthemeeting',
            name='meeting_number',
            field=models.IntegerField(blank=True, help_text='Enter the meeting number. Eg: 1st, 2nd, 3rd, etc.', null=True, verbose_name='Meeting Number'),
        ),
    ]
