# Generated by Django 5.0.1 on 2026-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0071_remove_historicalminutesofthemeeting_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalminutesofthemeeting',
            name='minutes_of_meeting',
            field=models.TextField(help_text='Upload Minutes of the meeting', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalschoolboardmom',
            name='minutes',
            field=models.TextField(help_text='Upload Minutes of the Meeting', max_length=100),
        ),
        migrations.AlterField(
            model_name='minutesofthemeeting',
            name='minutes_of_meeting',
            field=models.FileField(help_text='Upload Minutes of the meeting', upload_to='committees/minutes/'),
        ),
        migrations.AlterField(
            model_name='schoolboardmom',
            name='minutes',
            field=models.FileField(help_text='Upload Minutes of the Meeting', upload_to='schools/school-board-mom/'),
        ),
    ]
