# Generated by Django 5.0.1 on 2026-07-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0072_alter_historicalminutesofthemeeting_minutes_of_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(choices=[('DRC', 'Departmental Research Committee (DRC)'), ('BPGS', 'Board of Post Graduate Studies (BPGS)'), ('BUGS', 'Board of Under Graduate Studies (BUGS)'), ('DPC', 'Departmental Purchase Committee (DPC)'), ('Others', 'Others')], max_length=255, verbose_name='Name of Committee'),
        ),
        migrations.AlterField(
            model_name='historicalcommittee',
            name='name',
            field=models.CharField(choices=[('DRC', 'Departmental Research Committee (DRC)'), ('BPGS', 'Board of Post Graduate Studies (BPGS)'), ('BUGS', 'Board of Under Graduate Studies (BUGS)'), ('DPC', 'Departmental Purchase Committee (DPC)'), ('Others', 'Others')], max_length=255, verbose_name='Name of Committee'),
        ),
        migrations.AlterField(
            model_name='historicalminutesofthemeeting',
            name='meeting_title',
            field=models.CharField(blank=True, help_text='Title of the meeting', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='minutesofthemeeting',
            name='meeting_title',
            field=models.CharField(blank=True, help_text='Title of the meeting', max_length=155, null=True),
        ),
    ]
