# Generated by Django 5.0.1 on 2026-08-07 09:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='COENotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Notice Title')),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='coe/notices/')),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
            ],
            options={
                'verbose_name_plural': 'COE Notices & Circulars',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MPHILVivaVoceDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='coe/mphil_viva_voce_dates/')),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
            ],
            options={
                'verbose_name_plural': 'MPhil Viva Voce Dates',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PHDPreSubmissionSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='coe/phd_pre_submission_seminars/')),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
            ],
            options={
                'verbose_name_plural': 'PhD Pre-Submission Seminar Dates',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PHDVivaVoceDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='coe/phd_viva_voce_dates/')),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
            ],
            options={
                'verbose_name_plural': 'PhD Viva Voce Dates',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RDCUNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Notice Title')),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='coe/rdc_notices/')),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
            ],
            options={
                'verbose_name_plural': 'RDC Notices',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCOENotice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Notice Title')),
                ('date', models.DateField()),
                ('file', models.TextField(max_length=100)),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical coe notice',
                'verbose_name_plural': 'historical COE Notices & Circulars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMPHILVivaVoceDate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateField()),
                ('file', models.TextField(max_length=100)),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mphil viva voce date',
                'verbose_name_plural': 'historical MPhil Viva Voce Dates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPHDPreSubmissionSeminar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateField()),
                ('file', models.TextField(max_length=100)),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical phd pre submission seminar',
                'verbose_name_plural': 'historical PhD Pre-Submission Seminar Dates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPHDVivaVoceDate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateField()),
                ('file', models.TextField(max_length=100)),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical phd viva voce date',
                'verbose_name_plural': 'historical PhD Viva Voce Dates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRDCUNotice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Notice Title')),
                ('date', models.DateField()),
                ('file', models.TextField(max_length=100)),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rdcu notice',
                'verbose_name_plural': 'historical RDC Notices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
