# Generated by Django 5.0.1 on 2026-08-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmphilvivavocedate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mphil viva voce date', 'verbose_name_plural': 'historical MPhil Viva Voce Notices'},
        ),
        migrations.AlterModelOptions(
            name='historicalphdpresubmissionseminar',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical phd pre submission seminar', 'verbose_name_plural': 'historical PhD Pre-Submission Seminar Notices'},
        ),
        migrations.AlterModelOptions(
            name='historicalphdvivavocedate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical phd viva voce date', 'verbose_name_plural': 'historical PhD Viva Voce Notices'},
        ),
        migrations.AlterModelOptions(
            name='mphilvivavocedate',
            options={'ordering': ['-date'], 'verbose_name_plural': 'MPhil Viva Voce Notices'},
        ),
        migrations.AlterModelOptions(
            name='phdpresubmissionseminar',
            options={'ordering': ['-date'], 'verbose_name_plural': 'PhD Pre-Submission Seminar Notices'},
        ),
        migrations.AlterModelOptions(
            name='phdvivavocedate',
            options={'ordering': ['-date'], 'verbose_name_plural': 'PhD Viva Voce Notices'},
        ),
    ]
