# Generated by Django 5.0.1 on 2026-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
