# Generated by Django 5.0.1 on 2026-03-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_centre_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='director',
        ),
    ]
