# Generated by Django 5.0.1 on 2026-04-21 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0003_remove_centre_director'),
        ('faculty', '0019_alter_faculty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_centres', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='centre',
            name='head_title',
            field=models.CharField(blank=True, choices=[('Director', 'Director'), ('In-Charge', 'In-Charge'), ('Coordinator', 'Coordinator'), ('Others', 'Others')], help_text='The official title for the head of this specific centre.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='head_title_other',
            field=models.CharField(blank=True, help_text="Provide the title if 'Others' is selected", max_length=100, null=True),
        ),
    ]
