# Generated by Django 5.0.1 on 2026-04-22 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0004_centre_head_centre_head_title_and_more'),
        ('faculty', '0019_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_centres', to='faculty.faculty', verbose_name='Leadership'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='head_title',
            field=models.CharField(blank=True, choices=[('Director', 'Director'), ('In-Charge', 'In-Charge'), ('Coordinator', 'Coordinator'), ('Others', 'Others')], max_length=50, null=True, verbose_name='Leadership Title'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='head_title_other',
            field=models.CharField(blank=True, help_text="Provide the title if 'Others' is selected", max_length=100, null=True, verbose_name='Other Leadership Title'),
        ),
    ]
