# Generated by Django 5.0.1 on 2026-05-07 07:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0056_department_leadership_title_and_more'),
        ('centres', '0005_alter_centre_head_alter_centre_head_title_and_more'),
        ('faculty', '0025_historicalfaculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCentre',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('head_title', models.CharField(blank=True, choices=[('Director', 'Director'), ('In-Charge', 'In-Charge'), ('Coordinator', 'Coordinator'), ('Others', 'Others')], max_length=50, null=True, verbose_name='Leadership Title')),
                ('head_title_other', models.CharField(blank=True, help_text="Provide the title if 'Others' is selected", max_length=100, null=True, verbose_name='Other Leadership Title')),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('head', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faculty.faculty', verbose_name='Leadership')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.school')),
            ],
            options={
                'verbose_name': 'historical centre',
                'verbose_name_plural': 'historical centres',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
