# Generated by Django 5.0.1 on 2026-05-11 08:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0007_centre_deleted_at_centre_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='thrust_areas',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Major research and academic focus areas of the centre', null=True),
        ),
        migrations.AddField(
            model_name='historicalcentre',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcentre',
            name='thrust_areas',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Major research and academic focus areas of the centre', null=True),
        ),
    ]
