# Generated by Django 5.0.1 on 2026-05-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionbrochure',
            name='title',
            field=models.CharField(help_text='e.g., UG Prospectus 2026', max_length=255, verbose_name='Document Name'),
        ),
        migrations.AlterField(
            model_name='admissionlink',
            name='title',
            field=models.CharField(help_text='e.g., Apply Now, CUET Portal', max_length=255, verbose_name='Link Display Text'),
        ),
        migrations.AlterField(
            model_name='admissionupdate',
            name='title',
            field=models.CharField(help_text='The main heading for this update or announcement.', max_length=255, verbose_name='Subject / Headline'),
        ),
        migrations.AlterField(
            model_name='historicaladmissionbrochure',
            name='title',
            field=models.CharField(help_text='e.g., UG Prospectus 2026', max_length=255, verbose_name='Document Name'),
        ),
        migrations.AlterField(
            model_name='historicaladmissionlink',
            name='title',
            field=models.CharField(help_text='e.g., Apply Now, CUET Portal', max_length=255, verbose_name='Link Display Text'),
        ),
        migrations.AlterField(
            model_name='historicaladmissionupdate',
            name='title',
            field=models.CharField(help_text='The main heading for this update or announcement.', max_length=255, verbose_name='Subject / Headline'),
        ),
    ]
