# Generated by Django 5.0.1 on 2026-05-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_admissionbrochure_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionbrochure',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='admissioncontact',
            name='category',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionlink',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='admissionschedule',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='admissionupdate',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaladmissionbrochure',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaladmissioncontact',
            name='category',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaladmissionlink',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaladmissionschedule',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaladmissionupdate',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50),
        ),
    ]
