# Generated by Django 5.0.1 on 2026-05-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_alter_course_course_code_and_more'),
        ('admission', '0003_alter_admissionbrochure_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionbrochure',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Select specific departments if applicable.', to='academics.department'),
        ),
        migrations.AddField(
            model_name='admissionbrochure',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Select specific programs if applicable.', to='academics.program'),
        ),
        migrations.AddField(
            model_name='admissionschedule',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Select specific departments if applicable.', to='academics.department'),
        ),
        migrations.AddField(
            model_name='admissionschedule',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Select specific programs if applicable.', to='academics.program'),
        ),
        migrations.AddField(
            model_name='admissionsession',
            name='samarth_url',
            field=models.URLField(blank=True, help_text='Link to the Samarth admission portal for this session', null=True),
        ),
        migrations.AddField(
            model_name='admissionupdate',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Select specific departments if applicable.', to='academics.department'),
        ),
        migrations.AddField(
            model_name='admissionupdate',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Select specific programs if applicable.', to='academics.program'),
        ),
        migrations.AddField(
            model_name='historicaladmissionsession',
            name='samarth_url',
            field=models.URLField(blank=True, help_text='Link to the Samarth admission portal for this session', null=True),
        ),
    ]
