# Generated by Django 5.0.1 on 2026-05-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_admissionbrochure_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionsession',
            name='samarth_url',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionsession',
            name='samarth_url',
        ),
    ]
