# Generated by Django 5.0.1 on 2026-05-21 07:35

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_alter_course_course_code_and_more'),
        ('admission', '0005_remove_admissionsession_samarth_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionMeritList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='e.g., First Merit List for B.Tech', max_length=255, verbose_name='Merit List / Cutoff Title')),
                ('category', models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50)),
                ('other_category_name', models.CharField(blank=True, help_text="Specify if 'Others' is selected.", max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='admission/merit_lists/')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('departments', models.ManyToManyField(blank=True, help_text='Select specific departments if applicable.', to='academics.department')),
                ('programs', models.ManyToManyField(blank=True, help_text='Select specific programs if applicable.', to='academics.program')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='admission.admissionsession')),
            ],
            options={
                'ordering': ['-date_posted', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAdmissionMeritList',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='e.g., First Merit List for B.Tech', max_length=255, verbose_name='Merit List / Cutoff Title')),
                ('category', models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50)),
                ('other_category_name', models.CharField(blank=True, help_text="Specify if 'Others' is selected.", max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('attachment', models.TextField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.admissionsession')),
            ],
            options={
                'verbose_name': 'historical admission merit list',
                'verbose_name_plural': 'historical admission merit lists',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
