# Generated by Django 5.0.1 on 2026-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_admissionmeritlist_historicaladmissionmeritlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionbrochure',
            name='other_category_name',
            field=models.CharField(blank=True, help_text="Specify if 'Others' is selected.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaladmissionbrochure',
            name='other_category_name',
            field=models.CharField(blank=True, help_text="Specify if 'Others' is selected.", max_length=100, null=True),
        ),
    ]
