# Generated by Django 5.0.1 on 2026-06-04 06:22

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_alter_course_course_code_and_more'),
        ('admission', '0008_admissioncommitteemember_admissioncommitteeminutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissioncontact',
            name='session',
        ),
        migrations.RemoveField(
            model_name='admissionlink',
            name='session',
        ),
        migrations.RemoveField(
            model_name='admissionmeritlist',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='admissionmeritlist',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='admissionmeritlist',
            name='session',
        ),
        migrations.RemoveField(
            model_name='admissionschedule',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='admissionschedule',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='admissionschedule',
            name='session',
        ),
        migrations.RemoveField(
            model_name='admissionupdate',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='admissionupdate',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='admissionupdate',
            name='session',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionbrochure',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionbrochure',
            name='session',
        ),
        migrations.RemoveField(
            model_name='historicaladmissioncontact',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaladmissioncontact',
            name='session',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionlink',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionlink',
            name='session',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionmeritlist',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionmeritlist',
            name='session',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionschedule',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionschedule',
            name='session',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionupdate',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionupdate',
            name='session',
        ),
        migrations.CreateModel(
            name='AdmissionStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g., B.Tech via JEE, PG via CUET', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which tabs are displayed')),
                ('is_active', models.BooleanField(default=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='General instructions for this stream', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='admission.admissionsession')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionProspectus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='e.g., CUET PG Information Bulletin', max_length=255)),
                ('file', models.FileField(upload_to='admission/prospectuses/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectuses', to='admission.admissionstream')),
            ],
            options={
                'verbose_name_plural': 'Admission Prospectuses',
                'ordering': ['-upload_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='admission/notices/')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='admission.admissionstream')),
            ],
            options={
                'ordering': ['-date_posted', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CounsellingPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phase_name', models.CharField(help_text='e.g., Phase 1, Phase 2, Spot Counselling', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Chronological order of the phase')),
                ('is_active', models.BooleanField(default=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_phases', to='admission.admissionstream')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('list_type', models.CharField(choices=[('Merit', 'Merit List'), ('Interview', 'Interview List'), ('Selected', 'Selected Candidates'), ('Waitlist', 'Waitlisted Candidates'), ('Other', 'Other')], default='Merit', max_length=50)),
                ('pdf_file', models.FileField(upload_to='admission/departmental_results/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_results', to='academics.department')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmental_results', to='admission.counsellingphase')),
            ],
            options={
                'ordering': ['department__name', 'list_type', '-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAdmissionNotice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.TextField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.admissionstream')),
            ],
            options={
                'verbose_name': 'historical admission notice',
                'verbose_name_plural': 'historical admission notices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAdmissionProspectus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='e.g., CUET PG Information Bulletin', max_length=255)),
                ('file', models.TextField(max_length=100)),
                ('upload_date', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.admissionstream')),
            ],
            options={
                'verbose_name': 'historical admission prospectus',
                'verbose_name_plural': 'historical Admission Prospectuses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAdmissionStream',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g., B.Tech via JEE, PG via CUET', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which tabs are displayed')),
                ('is_active', models.BooleanField(default=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='General instructions for this stream', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.admissionsession')),
            ],
            options={
                'verbose_name': 'historical admission stream',
                'verbose_name_plural': 'historical admission streams',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCounsellingPhase',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phase_name', models.CharField(help_text='e.g., Phase 1, Phase 2, Spot Counselling', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Chronological order of the phase')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.admissionstream')),
            ],
            options={
                'verbose_name': 'historical counselling phase',
                'verbose_name_plural': 'historical counselling phases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDepartmentalResult',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('list_type', models.CharField(choices=[('Merit', 'Merit List'), ('Interview', 'Interview List'), ('Selected', 'Selected Candidates'), ('Waitlist', 'Waitlisted Candidates'), ('Other', 'Other')], default='Merit', max_length=50)),
                ('pdf_file', models.TextField(max_length=100)),
                ('upload_date', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.counsellingphase')),
            ],
            options={
                'verbose_name': 'historical departmental result',
                'verbose_name_plural': 'historical departmental results',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationPortal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('portal_name', models.CharField(help_text='e.g., Samarth CUET-PG Portal', max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.admissionstream')),
            ],
            options={
                'verbose_name': 'historical registration portal',
                'verbose_name_plural': 'historical registration portals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegistrationPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('portal_name', models.CharField(help_text='e.g., Samarth CUET-PG Portal', max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_portals', to='admission.admissionstream')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='AdmissionBrochure',
        ),
        migrations.DeleteModel(
            name='AdmissionContact',
        ),
        migrations.DeleteModel(
            name='AdmissionLink',
        ),
        migrations.DeleteModel(
            name='AdmissionMeritList',
        ),
        migrations.DeleteModel(
            name='AdmissionSchedule',
        ),
        migrations.DeleteModel(
            name='AdmissionUpdate',
        ),
        migrations.DeleteModel(
            name='HistoricalAdmissionBrochure',
        ),
        migrations.DeleteModel(
            name='HistoricalAdmissionContact',
        ),
        migrations.DeleteModel(
            name='HistoricalAdmissionLink',
        ),
        migrations.DeleteModel(
            name='HistoricalAdmissionMeritList',
        ),
        migrations.DeleteModel(
            name='HistoricalAdmissionSchedule',
        ),
        migrations.DeleteModel(
            name='HistoricalAdmissionUpdate',
        ),
    ]
