# Generated by Django 5.0.1 on 2026-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_remove_admissioncontact_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstream',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], default='UG', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaladmissionstream',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], default='UG', max_length=50),
        ),
    ]
