# Generated by Django 5.0.1 on 2026-06-04 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_alter_course_course_code_and_more'),
        ('admission', '0010_admissionstream_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalDepartmentalResult',
            new_name='HistoricalMeritList',
        ),
        migrations.AlterModelOptions(
            name='historicalmeritlist',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical merit list', 'verbose_name_plural': 'historical merit lists'},
        ),
        migrations.CreateModel(
            name='MeritList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('list_type', models.CharField(choices=[('Merit', 'Merit List'), ('Interview', 'Interview List'), ('Selected', 'Selected Candidates'), ('Waitlist', 'Waitlisted Candidates'), ('Other', 'Other')], default='Merit', max_length=50)),
                ('pdf_file', models.FileField(upload_to='admission/merit_lists/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_results', to='academics.department')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='admission.counsellingphase')),
            ],
            options={
                'ordering': ['department__name', 'list_type', '-upload_date'],
            },
        ),
        migrations.DeleteModel(
            name='DepartmentalResult',
        ),
    ]
