# Generated by Django 5.0.1 on 2026-06-05 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_rename_historicaldepartmentalresult_historicalmeritlist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionprospectus',
            options={'ordering': ['-upload_date', '-id'], 'verbose_name_plural': 'Admission Prospectus'},
        ),
        migrations.AlterModelOptions(
            name='admissionstream',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Admission Programs'},
        ),
        migrations.AlterModelOptions(
            name='counsellingphase',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Seat Allocation Rounds'},
        ),
        migrations.AlterModelOptions(
            name='historicaladmissionprospectus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical admission prospectus', 'verbose_name_plural': 'historical Admission Prospectus'},
        ),
        migrations.AlterModelOptions(
            name='historicaladmissionstream',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical admission stream', 'verbose_name_plural': 'historical Admission Programs'},
        ),
        migrations.AlterModelOptions(
            name='historicalcounsellingphase',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical counselling phase', 'verbose_name_plural': 'historical Seat Allocation Rounds'},
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionnotice',
            name='stream',
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], default='UG', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='admission.admissionsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaladmissionnotice',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], default='UG', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaladmissionnotice',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.admissionsession'),
        ),
    ]
