# Generated by Django 5.0.1 on 2026-06-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_alter_admissionprospectus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstream',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaladmissionstream',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], max_length=50),
        ),
    ]
