# Generated by Django 5.0.1 on 2026-06-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_alter_admissionnotice_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionprospectus',
            options={'ordering': ['-upload_date', '-id'], 'verbose_name_plural': 'Admission Prospectuses'},
        ),
        migrations.AlterModelOptions(
            name='historicaladmissionprospectus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical admission prospectus', 'verbose_name_plural': 'historical Admission Prospectuses'},
        ),
        migrations.RemoveField(
            model_name='admissionprospectus',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionprospectus',
            name='stream',
        ),
        migrations.AddField(
            model_name='admissionprospectus',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], default='UG', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionprospectus',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prospectuses', to='admission.admissionsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaladmissionprospectus',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], default='UG', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaladmissionprospectus',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.admissionsession'),
        ),
    ]
