# Generated by Django 5.0.1 on 2026-06-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_alter_admissionprospectus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionprospectus',
            options={'ordering': ['-upload_date', '-id'], 'verbose_name_plural': 'Admission Prospectus'},
        ),
        migrations.AlterModelOptions(
            name='historicaladmissionprospectus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical admission prospectus', 'verbose_name_plural': 'historical Admission Prospectus'},
        ),
    ]
