# Generated by Django 5.0.1 on 2026-06-05 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0016_alter_admissionprospectus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrationportal',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], default='UG', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalregistrationportal',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.admissionsession'),
        ),
        migrations.AddField(
            model_name='registrationportal',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)'), ('PHD', 'Ph.D.'), ('International', 'International'), ('Others', 'Others')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationportal',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registration_portals', to='admission.admissionsession'),
        ),
        migrations.AlterField(
            model_name='registrationportal',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_portals', to='admission.admissionstream'),
        ),
    ]
