# Generated by Django 5.0.1 on 2026-06-05 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_historicalregistrationportal_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistrationportal',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.admissionsession'),
        ),
        migrations.AlterField(
            model_name='registrationportal',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_portals', to='admission.admissionsession'),
        ),
    ]
