# Generated by Django 5.0.1 on 2026-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_alter_historicalregistrationportal_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistrationportal',
            name='session',
        ),
        migrations.RemoveField(
            model_name='registrationportal',
            name='session',
        ),
        migrations.AlterField(
            model_name='historicalregistrationportal',
            name='registration_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalregistrationportal',
            name='registration_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationportal',
            name='registration_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationportal',
            name='registration_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
