# Generated by Django 5.0.1 on 2026-06-05 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_remove_historicalregistrationportal_stream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationportal',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registration_portals', to='admission.admissionsession'),
            preserve_default=False,
        ),
    ]
