# Generated by Django 5.0.1 on 2026-06-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_alter_registrationportal_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionnotice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='admissionstream',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionnotice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicaladmissionstream',
            name='description',
        ),
    ]
