# Generated by Django 5.0.1 on 2026-06-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_remove_admissionnotice_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meritlist',
            options={'ordering': ['department__name', '-upload_date']},
        ),
        migrations.RemoveField(
            model_name='historicalmeritlist',
            name='list_type',
        ),
        migrations.RemoveField(
            model_name='meritlist',
            name='list_type',
        ),
    ]
