# Generated by Django 5.0.1 on 2026-06-09 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0023_alter_meritlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counsellingphase',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Admission Cutoff Rounds'},
        ),
        migrations.AlterModelOptions(
            name='historicalcounsellingphase',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical counselling phase', 'verbose_name_plural': 'historical Admission Cutoff Rounds'},
        ),
        migrations.AlterField(
            model_name='admissionnotice',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicaladmissionnotice',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
