# Generated by Django 5.0.1 on 2026-07-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_alter_counsellingphase_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='admissionstream',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('session', 'name'), name='unique_admission_stream_per_session'),
        ),
    ]
