# Generated by Django 5.0.1 on 2026-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_add_constraints_and_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncommitteeminutes',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True),
        ),
        migrations.AddField(
            model_name='admissioncommitteeminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive these minutes.'),
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which this notice automatically becomes archived.', null=True),
        ),
        migrations.AddField(
            model_name='admissionnotice',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive this notice.'),
        ),
        migrations.AddField(
            model_name='historicaladmissioncommitteeminutes',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True),
        ),
        migrations.AddField(
            model_name='historicaladmissioncommitteeminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive these minutes.'),
        ),
        migrations.AddField(
            model_name='historicaladmissionnotice',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which this notice automatically becomes archived.', null=True),
        ),
        migrations.AddField(
            model_name='historicaladmissionnotice',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive this notice.'),
        ),
    ]
