# Generated by Django 5.0.1 on 2026-07-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0067_cbcscourse_syllabus_historicalcbcscourse_syllabus'),
        ('admission', '0026_admissioncommitteeminutes_archive_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeritlist',
            name='programme',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.program'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_results', to='academics.program'),
        ),
    ]
