# Generated by Django 5.0.1 on 2026-07-28 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0067_cbcscourse_syllabus_historicalcbcscourse_syllabus'),
        ('admission', '0027_historicalmeritlist_programme_meritlist_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meritlist',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_results', to='academics.department'),
        ),
    ]
