# Generated by Django 5.0.1 on 2026-07-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0067_cbcscourse_syllabus_historicalcbcscourse_syllabus'),
        ('admission', '0028_alter_meritlist_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meritlist',
            options={'ordering': ['programme', '-upload_date']},
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_results', to='academics.program'),
        ),
    ]
