# Generated by Django 5.0.1 on 2026-07-01 07:53

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=10, verbose_name='Course Level')),
                ('semester', models.PositiveIntegerField(help_text='e.g., 1, 2, 3, 4...', verbose_name='Semester')),
                ('course_code', models.CharField(max_length=100, verbose_name='Course/Paper Code')),
                ('course_title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('credits', models.PositiveIntegerField(default=0, verbose_name='Credits')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('syllabus_file', models.FileField(blank=True, null=True, upload_to='foundation_courses/syllabus/', verbose_name='Syllabus File')),
                ('syllabus_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Syllabus Description/Text')),
            ],
            options={
                'verbose_name': 'Foundation Course',
                'verbose_name_plural': 'Foundation Courses',
                'ordering': ['level', 'semester', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='FoundationCourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Material Title')),
                ('material_type', models.CharField(choices=[('Document', 'Document/PDF'), ('Video', 'Video Lecture'), ('Link', 'External Link/Reference'), ('Others', 'Others')], default='Document', max_length=50, verbose_name='Material Type')),
                ('file', models.FileField(blank=True, null=True, upload_to='foundation_courses/materials/', verbose_name='File Attachment')),
                ('link', models.URLField(blank=True, null=True, verbose_name='External Link')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Foundation Course Material',
                'verbose_name_plural': 'Foundation Course Materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFoundationCourse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=10, verbose_name='Course Level')),
                ('semester', models.PositiveIntegerField(help_text='e.g., 1, 2, 3, 4...', verbose_name='Semester')),
                ('course_code', models.CharField(max_length=100, verbose_name='Course/Paper Code')),
                ('course_title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('credits', models.PositiveIntegerField(default=0, verbose_name='Credits')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('syllabus_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Syllabus File')),
                ('syllabus_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Syllabus Description/Text')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Foundation Course',
                'verbose_name_plural': 'historical Foundation Courses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFoundationCourseMaterial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Material Title')),
                ('material_type', models.CharField(choices=[('Document', 'Document/PDF'), ('Video', 'Video Lecture'), ('Link', 'External Link/Reference'), ('Others', 'Others')], default='Document', max_length=50, verbose_name='Material Type')),
                ('file', models.TextField(blank=True, max_length=100, null=True, verbose_name='File Attachment')),
                ('link', models.URLField(blank=True, null=True, verbose_name='External Link')),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False, verbose_name='Uploaded At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Foundation Course Material',
                'verbose_name_plural': 'historical Foundation Course Materials',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='foundationcourse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('course_code',), name='unique_foundation_course_code'),
        ),
        migrations.AddField(
            model_name='foundationcoursematerial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='foundation_course.foundationcourse', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='historicalfoundationcourse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfoundationcoursematerial',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='foundation_course.foundationcourse', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='historicalfoundationcoursematerial',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
