# Generated by Django 5.0.1 on 2026-07-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundationcourse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='foundationcourse',
            name='syllabus_text',
        ),
        migrations.RemoveField(
            model_name='historicalfoundationcourse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalfoundationcourse',
            name='syllabus_text',
        ),
    ]
