# Generated by Django 5.0.1 on 2026-07-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_course', '0002_remove_foundationcourse_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundationcoursematerial',
            name='other_material_type',
            field=models.CharField(blank=True, help_text="Please specify if material type is 'Others'.", max_length=100, null=True, verbose_name='Other Material Type'),
        ),
        migrations.AddField(
            model_name='historicalfoundationcoursematerial',
            name='other_material_type',
            field=models.CharField(blank=True, help_text="Please specify if material type is 'Others'.", max_length=100, null=True, verbose_name='Other Material Type'),
        ),
    ]
