# Generated by Django 5.0.1 on 2026-09-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiragging', '0002_alter_committeemember_options_alter_faq_options_and_more'),
        ('faculty', '0040_add_other_material_type_and_orcid_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='affiliation',
            field=models.CharField(blank=True, help_text='e.g., District Administration, Lucknow Police, NGO, Student, Parent, Non-Teaching Staff', max_length=150, verbose_name='Affiliation / Department / Organization'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='name',
            field=models.CharField(blank=True, help_text='Required if not selecting a faculty member above.', max_length=150, verbose_name='Member Name (for external / non-faculty)'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='other_designation',
            field=models.CharField(blank=True, help_text="Required if Designation is 'Other'", max_length=150, verbose_name='Specify Other Designation'),
        ),
        migrations.AddField(
            model_name='historicalcommitteemember',
            name='affiliation',
            field=models.CharField(blank=True, help_text='e.g., District Administration, Lucknow Police, NGO, Student, Parent, Non-Teaching Staff', max_length=150, verbose_name='Affiliation / Department / Organization'),
        ),
        migrations.AddField(
            model_name='historicalcommitteemember',
            name='name',
            field=models.CharField(blank=True, help_text='Required if not selecting a faculty member above.', max_length=150, verbose_name='Member Name (for external / non-faculty)'),
        ),
        migrations.AddField(
            model_name='historicalcommitteemember',
            name='other_designation',
            field=models.CharField(blank=True, help_text="Required if Designation is 'Other'", max_length=150, verbose_name='Specify Other Designation'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='designation',
            field=models.CharField(choices=[('', 'Select Designation'), ('CHAIRPERSON', 'Chairperson'), ('MEMBER', 'Member'), ('MEMBER_CONVENER', 'Member & Convener'), ('EXTERNAL_MEMBER', 'External Member'), ('POLICE_REP', 'Police Representative'), ('CIVIL_ADMIN_REP', 'Civil Administration Representative'), ('NGO_REP', 'NGO / Civil Society Representative'), ('MEDIA_REP', 'Media Representative'), ('PARENT_REP', 'Parent Representative'), ('STUDENT_REP', 'Student Representative'), ('NON_TEACHING_REP', 'Non-Teaching Staff Representative'), ('OTHER', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Select faculty member, or leave blank and enter name below for external/non-faculty members.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antiragging_committee_members', to='faculty.faculty', verbose_name='Faculty Member (if internal faculty)'),
        ),
        migrations.AlterField(
            model_name='historicalcommitteemember',
            name='designation',
            field=models.CharField(choices=[('', 'Select Designation'), ('CHAIRPERSON', 'Chairperson'), ('MEMBER', 'Member'), ('MEMBER_CONVENER', 'Member & Convener'), ('EXTERNAL_MEMBER', 'External Member'), ('POLICE_REP', 'Police Representative'), ('CIVIL_ADMIN_REP', 'Civil Administration Representative'), ('NGO_REP', 'NGO / Civil Society Representative'), ('MEDIA_REP', 'Media Representative'), ('PARENT_REP', 'Parent Representative'), ('STUDENT_REP', 'Student Representative'), ('NON_TEACHING_REP', 'Non-Teaching Staff Representative'), ('OTHER', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalcommitteemember',
            name='faculty',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select faculty member, or leave blank and enter name below for external/non-faculty members.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faculty.faculty', verbose_name='Faculty Member (if internal faculty)'),
        ),
    ]
