# Generated by Django 5.0.1 on 2026-09-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiragging', '0003_committeemember_affiliation_committeemember_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='designation',
            field=models.CharField(choices=[('', 'Select Designation'), ('CHAIRPERSON', 'Chairperson'), ('MEMBER', 'Member'), ('CONVENER', 'Convener'), ('MEMBER_CONVENER', 'Member & Convener'), ('OTHER', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='display_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalcommitteemember',
            name='designation',
            field=models.CharField(choices=[('', 'Select Designation'), ('CHAIRPERSON', 'Chairperson'), ('MEMBER', 'Member'), ('CONVENER', 'Convener'), ('MEMBER_CONVENER', 'Member & Convener'), ('OTHER', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalcommitteemember',
            name='display_order',
            field=models.PositiveIntegerField(),
        ),
    ]
