# Generated by Django 5.0.1 on 2026-09-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiragging', '0004_alter_committeemember_designation_and_more'),
        ('faculty', '0040_add_other_material_type_and_orcid_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='affiliation',
            field=models.CharField(blank=True, max_length=150, verbose_name='Designation in Committee'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Select faculty member, or leave blank and enter name below for external/non-teaching members.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antiragging_committee_members', to='faculty.faculty', verbose_name='Member Name (Faculty)'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='name',
            field=models.CharField(blank=True, help_text='Required if not selecting a faculty member above.', max_length=150, verbose_name='Member Name (Non-Teaching/External Member)'),
        ),
        migrations.AlterField(
            model_name='historicalcommitteemember',
            name='affiliation',
            field=models.CharField(blank=True, max_length=150, verbose_name='Designation in Committee'),
        ),
        migrations.AlterField(
            model_name='historicalcommitteemember',
            name='faculty',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select faculty member, or leave blank and enter name below for external/non-teaching members.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faculty.faculty', verbose_name='Member Name (Faculty)'),
        ),
        migrations.AlterField(
            model_name='historicalcommitteemember',
            name='name',
            field=models.CharField(blank=True, help_text='Required if not selecting a faculty member above.', max_length=150, verbose_name='Member Name (Non-Teaching/External Member)'),
        ),
    ]
