# Generated by Django 5.0.1 on 2026-09-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiragging', '0005_alter_committeemember_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencycontact',
            name='role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
