# Generated by Django 5.0.1 on 2026-09-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiragging', '0006_alter_emergencycontact_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalemergencycontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
