# Generated by Django 5.0.1 on 2026-06-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('partner_name', models.CharField(max_length=255, verbose_name='Partner/Organization Name')),
                ('mou_type', models.CharField(choices=[('Academic', 'Academic'), ('Industry', 'Industry'), ('International', 'International'), ('National', 'National'), ('Others', 'Others')], max_length=50, verbose_name='Type of MOU')),
                ('date_of_signing', models.DateField(verbose_name='Date of Signing')),
                ('valid_till', models.DateField(blank=True, null=True, verbose_name='Valid Till / Expiry Date')),
                ('description', models.TextField(help_text='Brief description (approx 200 words)')),
                ('document', models.FileField(blank=True, null=True, upload_to='mou_documents/', verbose_name='MOU Document')),
            ],
            options={
                'verbose_name': 'MOU',
                'verbose_name_plural': 'MOUs',
                'ordering': ['-date_of_signing'],
            },
        ),
    ]
