# Generated by Django 5.0.1 on 2026-06-18 12:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMOU',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('partner_name', models.CharField(max_length=255, verbose_name='Partner/Organization Name')),
                ('mou_type', models.CharField(choices=[('Academic', 'Academic'), ('Industry', 'Industry'), ('International', 'International'), ('National', 'National'), ('Others', 'Others')], max_length=50, verbose_name='Type of MOU')),
                ('date_of_signing', models.DateField(verbose_name='Date of Signing')),
                ('valid_till', models.DateField(blank=True, null=True, verbose_name='Valid Till / Expiry Date')),
                ('description', models.TextField(help_text='Brief description (approx 200 words)')),
                ('document', models.TextField(blank=True, max_length=100, null=True, verbose_name='MOU Document')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical MOU',
                'verbose_name_plural': 'historical MOUs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='mou',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('partner_name', 'mou_type', 'date_of_signing'), name='unique_mou_partner_type_date'),
        ),
        migrations.AddField(
            model_name='historicalmou',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
