# Generated by Django 5.0.1 on 2026-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0002_add_history_and_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mou',
            name='unique_mou_partner_type_date',
        ),
        migrations.RemoveField(
            model_name='historicalmou',
            name='mou_type',
        ),
        migrations.RemoveField(
            model_name='mou',
            name='mou_type',
        ),
        migrations.AddConstraint(
            model_name='mou',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('partner_name', 'date_of_signing'), name='unique_mou_partner_date'),
        ),
    ]
