# Generated by Django 5.0.1 on 2026-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0003_remove_mou_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmou',
            name='date_of_signing',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Signing'),
        ),
        migrations.AlterField(
            model_name='historicalmou',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description (approx 200 words)', null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='date_of_signing',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Signing'),
        ),
        migrations.AlterField(
            model_name='mou',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description (approx 200 words)', null=True),
        ),
    ]
