# Generated by Django 5.0.1 on 2026-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0004_alter_historicalmou_date_of_signing_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mou',
            name='unique_mou_partner_date',
        ),
        migrations.RenameField(
            model_name='historicalmou',
            old_name='partner_name',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='mou',
            old_name='partner_name',
            new_name='organization_name',
        ),
        migrations.AddField(
            model_name='historicalmou',
            name='Nature_of_organization',
            field=models.CharField(blank=True, choices=[('Central University', 'Central University'), ('State University', 'State University'), ('Centre', 'Centre'), ('Institution/Deemed University', 'Institution/Deemed University'), ('Research Organisation', 'Research Organisation'), ('Govt Department', 'Govt Department'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mou',
            name='Nature_of_organization',
            field=models.CharField(blank=True, choices=[('Central University', 'Central University'), ('State University', 'State University'), ('Centre', 'Centre'), ('Institution/Deemed University', 'Institution/Deemed University'), ('Research Organisation', 'Research Organisation'), ('Govt Department', 'Govt Department'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='mou',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization_name', 'date_of_signing'), name='unique_mou_partner_date'),
        ),
    ]
