# Generated by Django 5.0.1 on 2026-06-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0005_remove_mou_unique_mou_partner_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmou',
            name='other_nature_of_organization',
            field=models.CharField(blank=True, help_text="Please specify if 'Others' is selected", max_length=255, null=True, verbose_name='Other Nature of Organization'),
        ),
        migrations.AddField(
            model_name='mou',
            name='other_nature_of_organization',
            field=models.CharField(blank=True, help_text="Please specify if 'Others' is selected", max_length=255, null=True, verbose_name='Other Nature of Organization'),
        ),
    ]
