# Generated by Django 5.0.1 on 2026-07-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0006_historicalmou_other_nature_of_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmou',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive this MOU.'),
        ),
        migrations.AddField(
            model_name='mou',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive this MOU.'),
        ),
    ]
