# Generated by Django 5.0.1 on 2026-07-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0007_historicalmou_is_archived_mou_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmou',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which this MOU automatically becomes archived.', null=True),
        ),
        migrations.AddField(
            model_name='mou',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which this MOU automatically becomes archived.', null=True),
        ),
    ]
