# Generated by Django 5.0.1 on 2026-08-06 06:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of the Member')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, help_text='Phone numbers', max_length=255, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='For S.No sorting')),
            ],
            options={
                'verbose_name_plural': 'Proctorial Board Members',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProctorialBoardMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_title', models.CharField(max_length=255)),
                ('date_of_meeting', models.DateField()),
                ('file', models.FileField(upload_to='proctorial_board/minutes/')),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Proctorial Board Minutes',
                'ordering': ['-date_of_meeting'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProctorialBoardMember',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of the Member')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, help_text='Phone numbers', max_length=255, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='For S.No sorting')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proctorial board member',
                'verbose_name_plural': 'historical Proctorial Board Members',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProctorialBoardMinutes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_title', models.CharField(max_length=255)),
                ('date_of_meeting', models.DateField()),
                ('file', models.TextField(max_length=100)),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proctorial board minutes',
                'verbose_name_plural': 'historical Proctorial Board Minutes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
