# Generated by Django 5.0.1 on 2026-08-06 11:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorialBoardNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='proctorial_board/notices/')),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Proctorial Board Notices & Circulars',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='historicalproctorialboardmember',
            name='in_the_capacity_of',
            field=models.CharField(blank=True, choices=[('Proctor', 'Proctor'), ('Additional Proctor', 'Additional Proctor'), ('Dy. Proctor', 'Depty Proctor'), ('Asst. Proctor', 'Assistant Proctor'), ('Asst. Proctor & Convener', 'Assistant Proctor & Convener'), ('Others', 'Others')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalproctorialboardmember',
            name='notification',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproctorialboardmember',
            name='others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proctorialboardmember',
            name='in_the_capacity_of',
            field=models.CharField(blank=True, choices=[('Proctor', 'Proctor'), ('Additional Proctor', 'Additional Proctor'), ('Dy. Proctor', 'Depty Proctor'), ('Asst. Proctor', 'Assistant Proctor'), ('Asst. Proctor & Convener', 'Assistant Proctor & Convener'), ('Others', 'Others')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proctorialboardmember',
            name='notification',
            field=models.FileField(blank=True, null=True, upload_to='proctorial_board/notifications/'),
        ),
        migrations.AddField(
            model_name='proctorialboardmember',
            name='others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalProctorialBoardNotice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('file', models.TextField(max_length=100)),
                ('is_archived', models.BooleanField(default=False, help_text='Tick if want to add into archive.')),
                ('archive_date', models.DateField(blank=True, help_text='The date after which this automatically becomes archived.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proctorial board notice',
                'verbose_name_plural': 'historical Proctorial Board Notices & Circulars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
