# Generated by Django 5.0.1 on 2026-08-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0002_proctorialboardnotice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproctorialboardmember',
            old_name='others',
            new_name='others_in_the_capacity_of',
        ),
        migrations.RenameField(
            model_name='proctorialboardmember',
            old_name='others',
            new_name='others_in_the_capacity_of',
        ),
    ]
