# Generated by Django 5.0.1 on 2026-08-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0003_rename_others_historicalproctorialboardmember_others_in_the_capacity_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproctorialboardmember',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='proctorialboardmember',
            name='notification',
        ),
    ]
