# Generated by Django 5.0.1 on 2026-09-02 19:57

import apps.affidavits.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affidavit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('roll_number', models.CharField(help_text="Student's roll no.", max_length=50)),
                ('enrollment_number', models.CharField(help_text="Student's enrollment no.", max_length=50)),
                ('program_name', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('student_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')], verbose_name='Student Phone')),
                ('student_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='Student Email')),
                ('parent_name', models.CharField(blank=True, help_text='Required for parent affidavits', max_length=150)),
                ('parent_phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')], verbose_name='Parent Phone')),
                ('student_affidavit', models.FileField(upload_to=apps.affidavits.models.student_affidavit_path)),
                ('parent_affidavit', models.FileField(upload_to=apps.affidavits.models.parent_affidavit_path)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_verification', 'Under Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Verification remarks, visible to the submitter on tracking page')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Affidavit Submission',
                'verbose_name_plural': 'Affidavit Submissions',
                'ordering': ['-submitted_on'],
            },
        ),
        migrations.CreateModel(
            name='AffidavitFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Affidavits FAQ',
                'verbose_name_plural': 'Affidavits FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AffidavitGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Affidavits Guideline',
                'verbose_name_plural': 'Affidavits Guidelines',
            },
        ),
        migrations.CreateModel(
            name='SampleAffidavit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='affidavits/sample/')),
                ('affidavit_category', models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent')], max_length=20)),
            ],
            options={
                'verbose_name': 'Sample Affidavit',
                'verbose_name_plural': 'Sample Affidavits',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAffidavit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.CharField(db_index=True, editable=False, max_length=20)),
                ('student_name', models.CharField(max_length=150)),
                ('roll_number', models.CharField(help_text="Student's roll no.", max_length=50)),
                ('enrollment_number', models.CharField(help_text="Student's enrollment no.", max_length=50)),
                ('program_name', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('student_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')], verbose_name='Student Phone')),
                ('student_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='Student Email')),
                ('parent_name', models.CharField(blank=True, help_text='Required for parent affidavits', max_length=150)),
                ('parent_phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')], verbose_name='Parent Phone')),
                ('student_affidavit', models.TextField(max_length=100)),
                ('parent_affidavit', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_verification', 'Under Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Verification remarks, visible to the submitter on tracking page')),
                ('submitted_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Affidavit Submission',
                'verbose_name_plural': 'historical Affidavit Submissions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAffidavitFAQ',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Affidavits FAQ',
                'verbose_name_plural': 'historical Affidavits FAQs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAffidavitGuidelines',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Affidavits Guideline',
                'verbose_name_plural': 'historical Affidavits Guidelines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSampleAffidavit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.TextField(max_length=100)),
                ('affidavit_category', models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent')], max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sample Affidavit',
                'verbose_name_plural': 'historical Sample Affidavits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
