# Generated by Django 5.0.1 on 2026-09-02 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0073_alter_committee_name_alter_historicalcommittee_name_and_more'),
        ('affidavits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affidavit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affidavits', to='academics.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='affidavit',
            name='parent_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalaffidavit',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='historicalaffidavit',
            name='parent_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
