# Generated by Django 5.0.1 on 2026-03-24 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0009_remove_department_centre'),
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('staff_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('insti_email', models.EmailField(blank=True, max_length=254)),
                ('other_email', models.EmailField(blank=True, max_length=254)),
                ('phone1', models.CharField(blank=True, max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('research_int', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='centres.centre')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='academics.department')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='academics.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(condition=models.Q(('roles', 'DEAN')), fields=('school',), name='one_dean_per_school'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(condition=models.Q(('roles', 'HOD')), fields=('department',), name='one_hod_per_department'),
        ),
    ]
