# Generated by Django 5.0.1 on 2026-03-24 07:59
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculty_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='centre',
            field=models.ForeignKey(
                to='centres.centre',
                null=True,
                blank=True,
                on_delete=models.SET_NULL,
                related_name='faculty'
            ),
        ),
    ]
