# Generated by Django 5.0.1 on 2026-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_department_about_department_contact_email_and_more'),
        ('centres', '0003_remove_centre_director'),
        ('faculty', '0003_add_centre_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='faculty',
            name='one_dean_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='faculty',
            name='one_hod_per_department',
        ),
        migrations.AddField(
            model_name='faculty',
            name='photo_alt_text',
            field=models.CharField(blank=True, help_text='GIGW accessibility text for the image', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(condition=models.Q(('roles__contains', ['DEAN'])), fields=('school',), name='one_dean_per_school'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(condition=models.Q(('roles__contains', ['HOD'])), fields=('department',), name='one_hod_per_department'),
        ),
    ]
