# Generated by Django 5.0.1 on 2026-04-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_remove_faculty_one_dean_per_school_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='faculty',
            name='one_dean_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='faculty',
            name='one_hod_per_department',
        ),
    ]
