# Generated by Django 5.0.1 on 2026-04-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_remove_faculty_one_dean_per_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
