# Generated by Django 5.0.1 on 2026-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_faculty_dob_alter_faculty_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
