# Generated by Django 5.0.1 on 2026-04-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_alter_faculty_phone1_alter_faculty_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='insti_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='other_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
