# Generated by Django 5.0.1 on 2026-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_alter_faculty_insti_email_alter_faculty_other_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], default='Teaching', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='qualification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_exp',
            field=models.CharField(blank=True, help_text='e.g., 5 Years', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='teaching_exp',
            field=models.CharField(blank=True, help_text='e.g., 10 Years 6 Months', max_length=100),
        ),
    ]
