# Generated by Django 5.0.1 on 2026-04-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_faculty_campus_faculty_faculty_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='employee_id',
        ),
    ]
