# Generated by Django 5.0.1 on 2026-04-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_remove_faculty_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], max_length=50),
        ),
    ]
