# Generated by Django 5.0.1 on 2026-04-14 07:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_alter_faculty_campus_alter_faculty_faculty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='research_exp',
            field=ckeditor.fields.RichTextField(blank=True, help_text='e.g., 5 Years'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_int',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
