# Generated by Django 5.0.1 on 2026-04-14 07:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_alter_faculty_research_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='qualification',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_exp',
            field=models.TextField(blank=True, help_text='e.g., 5 Years'),
        ),
    ]
