# Generated by Django 5.0.1 on 2026-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_alter_faculty_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_exp',
            field=models.TextField(blank=True, help_text='e.g., 5 Years', max_length=100),
        ),
    ]
