# Generated by Django 5.0.1 on 2026-04-14 09:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_alter_faculty_phone1_alter_faculty_phone2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='cv_document',
            field=models.FileField(blank=True, help_text='Upload CV/Resume in PDF format', null=True, upload_to='faculty_cvs/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='google_scholar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck if the faculty member leaves the university'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal or lab website'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
