# Generated by Django 5.0.1 on 2026-04-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_faculty_cv_document_faculty_date_of_joining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_type',
        ),
    ]
