# Generated by Django 5.0.1 on 2026-04-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0016_remove_faculty_faculty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='date_of_superannuation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_gate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='scopus_url',
            field=models.URLField(blank=True),
        ),
    ]
