# Generated by Django 5.0.1 on 2026-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_faculty_date_of_superannuation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='research_exp',
            field=models.CharField(blank=True, help_text='e.g., 5 Years', max_length=100),
        ),
    ]
