# Generated by Django 5.0.1 on 2026-04-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_alter_faculty_research_exp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name_plural': 'Faculty'},
        ),
    ]
