# Generated by Django 5.0.1 on 2026-04-22 10:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0019_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='google_scholar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualification',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_exp',
            field=models.CharField(blank=True, help_text='e.g., 5 Years', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_gate_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_int',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='scopus_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='teaching_exp',
            field=models.CharField(blank=True, help_text='e.g., 10 Years 6 Months', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal or lab website', null=True),
        ),
    ]
