# Generated by Django 5.0.1 on 2026-04-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0020_alter_faculty_bio_alter_faculty_google_scholar_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty'},
        ),
    ]
