# Generated by Django 5.0.1 on 2026-04-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0021_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name_plural': 'Faculty'},
        ),
    ]
