# Generated by Django 5.0.1 on 2026-04-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0022_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='staff_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
