# Generated by Django 5.0.1 on 2026-04-29 12:52

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0036_historicaldepartment_historicalschool'),
        ('centres', '0005_alter_centre_head_alter_centre_head_title_and_more'),
        ('faculty', '0024_faculty_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFaculty',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('staff_no', models.PositiveIntegerField(db_index=True)),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('photo_alt_text', models.CharField(blank=True, help_text='GIGW accessibility text for the image', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('campus', models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], max_length=50)),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('qualification', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('teaching_exp', models.CharField(blank=True, help_text='e.g., 10 Years 6 Months', max_length=100, null=True)),
                ('research_exp', models.CharField(blank=True, help_text='e.g., 5 Years', max_length=100, null=True)),
                ('research_int', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('google_scholar_url', models.URLField(blank=True, null=True)),
                ('scopus_url', models.URLField(blank=True, null=True)),
                ('research_gate_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, help_text='Personal or lab website', null=True)),
                ('cv_document', models.TextField(blank=True, help_text='Upload CV/Resume in PDF format', max_length=100, null=True)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('insti_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('other_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone1', models.CharField(blank=True, max_length=10, null=True)),
                ('phone2', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_superannuation', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if the faculty member leaves the university')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('centre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centres.centre')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.school')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Link this faculty record to a user account for login access.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical faculty',
                'verbose_name_plural': 'historical Faculty',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
