# Generated by Django 5.0.1 on 2026-05-27 21:52

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0026_faculty_deleted_at_faculty_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvitedTalk',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Title of the talk', max_length=500)),
                ('event_name', models.CharField(help_text='Name of the event or conference', max_length=500)),
                ('role', models.CharField(blank=True, help_text='e.g., Keynote Speaker, Session Chair, Guest Lecturer', max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, help_text='Location of the event', max_length=500, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Additional details about the talk', null=True)),
                ('link', models.URLField(blank=True, help_text='Link to the event or talk video/slides', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('faculty', models.ForeignKey(blank=True, db_constraint=False, help_text='Faculty member who gave the talk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faculty.faculty')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Invited Talk',
                'verbose_name_plural': 'historical Invited Talks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InvitedTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Title of the talk', max_length=500)),
                ('event_name', models.CharField(help_text='Name of the event or conference', max_length=500)),
                ('role', models.CharField(blank=True, help_text='e.g., Keynote Speaker, Session Chair, Guest Lecturer', max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, help_text='Location of the event', max_length=500, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Additional details about the talk', null=True)),
                ('link', models.URLField(blank=True, help_text='Link to the event or talk video/slides', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Faculty member who gave the talk', on_delete=django.db.models.deletion.CASCADE, related_name='invited_talks', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'Invited Talk',
                'verbose_name_plural': 'Invited Talks',
                'ordering': ['-date', 'title'],
            },
        ),
    ]
