# Generated by Django 5.0.1 on 2026-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0027_historicalinvitedtalk_invitedtalk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvitedtalk',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invitedtalk',
            name='description',
        ),
        migrations.AlterField(
            model_name='historicalinvitedtalk',
            name='event_name',
            field=models.CharField(help_text='Name of the event', max_length=500),
        ),
        migrations.AlterField(
            model_name='invitedtalk',
            name='event_name',
            field=models.CharField(help_text='Name of the event', max_length=500),
        ),
    ]
