# Generated by Django 5.0.1 on 2026-05-27 22:34

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0029_alter_historicalinvitedtalk_event_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('course_name', models.CharField(help_text='Name of the course designed', max_length=500, verbose_name='Course Name')),
                ('course_level', models.CharField(blank=True, help_text='e.g., UG, PG, PhD, Diploma', max_length=50, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Additional details about the course', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Faculty member who designed the course', on_delete=django.db.models.deletion.CASCADE, related_name='course_designs', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'Course Design',
                'verbose_name_plural': 'Course Designs',
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCourseDesign',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('course_name', models.CharField(help_text='Name of the course designed', max_length=500, verbose_name='Course Name')),
                ('course_level', models.CharField(blank=True, help_text='e.g., UG, PG, PhD, Diploma', max_length=50, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Additional details about the course', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('faculty', models.ForeignKey(blank=True, db_constraint=False, help_text='Faculty member who designed the course', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faculty.faculty')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Course Design',
                'verbose_name_plural': 'historical Course Designs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
