# Generated by Django 5.0.1 on 2026-05-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0030_coursedesign_historicalcoursedesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedesign',
            name='other_level',
            field=models.CharField(blank=True, help_text="Please specify the level if 'Others' is selected", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcoursedesign',
            name='other_level',
            field=models.CharField(blank=True, help_text="Please specify the level if 'Others' is selected", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursedesign',
            name='course_level',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('Integrated', 'Integrated'), ('PHD', 'PhD'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoursedesign',
            name='course_level',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('Integrated', 'Integrated'), ('PHD', 'PhD'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
