# Generated by Django 5.0.1 on 2026-05-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0031_coursedesign_other_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedesign',
            old_name='other_level',
            new_name='other_course_level',
        ),
        migrations.RenameField(
            model_name='historicalcoursedesign',
            old_name='other_level',
            new_name='other_course_level',
        ),
    ]
