# Generated by Django 5.0.1 on 2026-05-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0033_historicalmembership_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembership',
            name='order_no',
            field=models.CharField(blank=True, help_text='Order Number', max_length=30, null=True, verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='membership',
            name='order_no',
            field=models.CharField(blank=True, help_text='Order Number', max_length=30, null=True, verbose_name='Order Number'),
        ),
    ]
