# Generated by Django 5.0.1 on 2026-05-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0034_historicalmembership_order_no_membership_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmembership',
            name='order_no',
            field=models.CharField(blank=True, help_text='Order number (e.g. ABC123XYZ)', max_length=30, null=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='order_no',
            field=models.CharField(blank=True, help_text='Order number (e.g. ABC123XYZ)', max_length=30, null=True, verbose_name='Order Number'),
        ),
    ]
