# Generated by Django 5.0.1 on 2026-05-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0035_alter_historicalmembership_order_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedesign',
            name='nature_of_contribution',
            field=models.TextField(blank=True, help_text='Nature of contribution eg: Alone, Team Member', null=True),
        ),
        migrations.AddField(
            model_name='historicalcoursedesign',
            name='nature_of_contribution',
            field=models.TextField(blank=True, help_text='Nature of contribution eg: Alone, Team Member', null=True),
        ),
    ]
