# Generated by Django 5.0.1 on 2026-06-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0037_faculty_orcid_id_historicalfaculty_orcid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='orcid_id',
            field=models.CharField(help_text='ORCID ID (e.g., 0000-0003-0902-4386)', max_length=19, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalfaculty',
            name='orcid_id',
            field=models.CharField(db_index=True, help_text='ORCID ID (e.g., 0000-0003-0902-4386)', max_length=19, null=True),
        ),
    ]
