# Generated by Django 5.0.1 on 2026-06-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0038_alter_faculty_orcid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='orcid_id',
            field=models.CharField(blank=True, help_text='ORCID ID (e.g., 0000-0003-0902-4386)', max_length=19, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalfaculty',
            name='orcid_id',
            field=models.CharField(blank=True, db_index=True, help_text='ORCID ID (e.g., 0000-0003-0902-4386)', max_length=19, null=True),
        ),
    ]
