# Generated by Django 5.0.1 on 2026-07-07 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0039_alter_faculty_orcid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='orcid_id',
            field=models.CharField(blank=True, help_text='ORCID ID (e.g., 0000-0003-0902-4386)', max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ORCID ID must be in the format XXXX-XXXX-XXXX-XXXX (e.g., 0000-0003-0902-4386).', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$')]),
        ),
        migrations.AlterField(
            model_name='historicalfaculty',
            name='orcid_id',
            field=models.CharField(blank=True, db_index=True, help_text='ORCID ID (e.g., 0000-0003-0902-4386)', max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='ORCID ID must be in the format XXXX-XXXX-XXXX-XXXX (e.g., 0000-0003-0902-4386).', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$')]),
        ),
    ]
