# Generated by Django 5.0.1 on 2026-09-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0040_add_other_material_type_and_orcid_validator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='historicalfaculty',
            name='roles',
        ),
    ]
