# Generated by Django 5.0.1 on 2026-09-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0041_remove_faculty_roles_remove_historicalfaculty_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Guest Faculty', 'Guest Faculty'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfaculty',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Guest Faculty', 'Guest Faculty'), ('Others', 'Others')], max_length=255),
        ),
    ]
