# Generated by Django 5.0.1 on 2026-09-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0042_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='others_designation',
            field=models.CharField(blank=True, help_text='Enter your designation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalfaculty',
            name='others_designation',
            field=models.CharField(blank=True, help_text='Enter your designation', max_length=255, null=True),
        ),
    ]
