# Generated by Django 5.0.1 on 2026-09-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0043_faculty_others_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Senior Professor', 'Senior Professor'), ('Guest Faculty', 'Guest Faculty'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfaculty',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Senior Professor', 'Senior Professor'), ('Guest Faculty', 'Guest Faculty'), ('Others', 'Others')], max_length=255),
        ),
    ]
