# Generated by Django 5.0.1 on 2026-05-13 07:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(choices=[('ACADEMIC_COUNCIL', 'Academic Council'), ('BOARD_OF_MANAGEMENT', 'Board of Management'), ('PLANNING_BOARD', 'Planning Board'), ('FINANCE_COMMITTEE', 'Finance Committee')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Authorities',
            },
        ),
        migrations.CreateModel(
            name='AuthorityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provision', models.CharField(blank=True, help_text='e.g., 11(1)(i)', max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_fax', models.TextField(blank=True, help_text='Multiple numbers allowed', null=True)),
                ('date_of_nomination', models.DateField(blank=True, null=True, verbose_name='Date of Nomination/Appointment')),
                ('date_of_expiry', models.DateField(blank=True, null=True)),
                ('capacity', models.CharField(blank=True, help_text='e.g., Ex-Officio, Chairman, etc.', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='For S.No sorting')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='authorities.authority')),
            ],
            options={
                'verbose_name_plural': 'Authority Members',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuthorityMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_title', models.CharField(max_length=255)),
                ('date_of_meeting', models.DateField()),
                ('file', models.FileField(upload_to='authorities/minutes/')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='authorities.authority')),
            ],
            options={
                'verbose_name_plural': 'Authority Minutes',
                'ordering': ['-date_of_meeting'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAuthority',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(choices=[('ACADEMIC_COUNCIL', 'Academic Council'), ('BOARD_OF_MANAGEMENT', 'Board of Management'), ('PLANNING_BOARD', 'Planning Board'), ('FINANCE_COMMITTEE', 'Finance Committee')], db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical authority',
                'verbose_name_plural': 'historical Authorities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAuthorityMember',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provision', models.CharField(blank=True, help_text='e.g., 11(1)(i)', max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_fax', models.TextField(blank=True, help_text='Multiple numbers allowed', null=True)),
                ('date_of_nomination', models.DateField(blank=True, null=True, verbose_name='Date of Nomination/Appointment')),
                ('date_of_expiry', models.DateField(blank=True, null=True)),
                ('capacity', models.CharField(blank=True, help_text='e.g., Ex-Officio, Chairman, etc.', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='For S.No sorting')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('authority', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authorities.authority')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical authority member',
                'verbose_name_plural': 'historical Authority Members',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAuthorityMinutes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_title', models.CharField(max_length=255)),
                ('date_of_meeting', models.DateField()),
                ('file', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('authority', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authorities.authority')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical authority minutes',
                'verbose_name_plural': 'historical Authority Minutes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
