# Generated by Django 5.0.1 on 2026-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='description',
        ),
        migrations.RemoveField(
            model_name='authoritymember',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='authoritymember',
            name='institution_address',
        ),
        migrations.RemoveField(
            model_name='historicalauthority',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalauthoritymember',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='historicalauthoritymember',
            name='institution_address',
        ),
        migrations.AlterField(
            model_name='authoritymember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of the Member'),
        ),
        migrations.AlterField(
            model_name='historicalauthoritymember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of the Member'),
        ),
    ]
