# Generated by Django 5.0.1 on 2026-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0003_academiccouncilmember_academiccouncilminutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplanningboardmember',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalplanningboardmember',
            name='institution',
            field=models.CharField(blank=True, help_text='University or organization details', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planningboardmember',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planningboardmember',
            name='institution',
            field=models.CharField(blank=True, help_text='University or organization details', max_length=255, null=True),
        ),
    ]
