# Generated by Django 5.0.1 on 2026-05-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0004_historicalplanningboardmember_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financecommitteemember',
            name='institution',
            field=models.CharField(blank=True, help_text='University or organization details', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalfinancecommitteemember',
            name='institution',
            field=models.CharField(blank=True, help_text='University or organization details', max_length=255, null=True),
        ),
    ]
