# Generated by Django 5.0.1 on 2026-05-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0005_financecommitteemember_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccouncilminutes',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, these minutes will only be visible to specific users.'),
        ),
        migrations.AddField(
            model_name='boardofmanagementminutes',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, these minutes will only be visible to specific users.'),
        ),
        migrations.AddField(
            model_name='financecommitteeminutes',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, these minutes will only be visible to specific users.'),
        ),
        migrations.AddField(
            model_name='historicalacademiccouncilminutes',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, these minutes will only be visible to specific users.'),
        ),
        migrations.AddField(
            model_name='historicalboardofmanagementminutes',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, these minutes will only be visible to specific users.'),
        ),
        migrations.AddField(
            model_name='historicalfinancecommitteeminutes',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, these minutes will only be visible to specific users.'),
        ),
        migrations.AddField(
            model_name='historicalplanningboardminutes',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, these minutes will only be visible to specific users.'),
        ),
        migrations.AddField(
            model_name='planningboardminutes',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If checked, these minutes will only be visible to specific users.'),
        ),
    ]
