# Generated by Django 5.0.1 on 2026-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0006_academiccouncilminutes_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccouncilminutes',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True),
        ),
        migrations.AddField(
            model_name='academiccouncilminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive these minutes.'),
        ),
        migrations.AddField(
            model_name='boardofmanagementminutes',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True),
        ),
        migrations.AddField(
            model_name='boardofmanagementminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive these minutes.'),
        ),
        migrations.AddField(
            model_name='financecommitteeminutes',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True),
        ),
        migrations.AddField(
            model_name='financecommitteeminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive these minutes.'),
        ),
        migrations.AddField(
            model_name='historicalacademiccouncilminutes',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True),
        ),
        migrations.AddField(
            model_name='historicalacademiccouncilminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive these minutes.'),
        ),
        migrations.AddField(
            model_name='historicalboardofmanagementminutes',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True),
        ),
        migrations.AddField(
            model_name='historicalboardofmanagementminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive these minutes.'),
        ),
        migrations.AddField(
            model_name='historicalfinancecommitteeminutes',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True),
        ),
        migrations.AddField(
            model_name='historicalfinancecommitteeminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive these minutes.'),
        ),
        migrations.AddField(
            model_name='historicalplanningboardminutes',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True),
        ),
        migrations.AddField(
            model_name='historicalplanningboardminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive these minutes.'),
        ),
        migrations.AddField(
            model_name='planningboardminutes',
            name='archive_date',
            field=models.DateField(blank=True, help_text='The date after which these minutes automatically become archived.', null=True),
        ),
        migrations.AddField(
            model_name='planningboardminutes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Manually archive these minutes.'),
        ),
    ]
