# Generated by Django 5.0.1 on 2026-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0003_complaint_manage_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='other_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('corruption', 'Corruption'), ('malpractice', 'Malpractice'), ('procedural_lapse', 'Procedural Lapse'), ('others', 'Others')], default='other', max_length=50),
        ),
    ]
