# Generated by Django 5.0.1 on 2026-08-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0004_complaint_other_status_alter_complaint_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='other_status',
            new_name='others_status',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('corruption', 'Corruption'), ('malpractice', 'Malpractice'), ('procedural_lapse', 'Procedural Lapse')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('forwarded', 'Forwarded to Higher Authorities'), ('dismissed', 'Dismissed'), ('others', 'Others')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintactionlog',
            name='status_changed_to',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('forwarded', 'Forwarded to Higher Authorities'), ('dismissed', 'Dismissed'), ('others', 'Others')], max_length=30, null=True),
        ),
    ]
