# Generated by Django 5.0.1 on 2026-08-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0005_rename_other_status_complaint_others_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('corruption', 'Corruption'), ('malpractice', 'Malpractice'), ('procedural_lapse', 'Procedural Lapse'), ('Others', 'Others')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('forwarded', 'Forwarded to Higher Authorities'), ('dismissed', 'Dismissed'), ('Others', 'Others')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintactionlog',
            name='action_description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='complaintactionlog',
            name='status_changed_to',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('forwarded', 'Forwarded to Higher Authorities'), ('dismissed', 'Dismissed'), ('Others', 'Others')], max_length=30, null=True),
        ),
    ]
