# Generated by Django 5.0.1 on 2026-08-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_grievance_manage_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='complainant_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('non_teaching_staff', 'Non Teaching Staff'), ('Other', 'Other')], max_length=50, verbose_name='Complainant'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='nature_of_grievance',
            field=models.CharField(choices=[('admission_contrary_to_merit', 'Making admission contrary to merit'), ('irregularity_in_admission', 'Irregularity in the admission process'), ('refusing_admission', 'Refusing admission in accordance with the declared admission policy of the institute'), ('non_publication_of_prospectus', 'Non publication of prospectus'), ('false_misleading_prospectus', 'Publishing false or misleading information in the prospectus'), ('withhold_documents', 'Withhold or refuse to return any document (certificates/degree/diploma or any other award/document for the purpose of seeking admission)'), ('excess_fee_demand', 'Demand of money in excess of that specified in the declared admission policy'), ('reservation_policy_breach', 'Breach of the policy for reservation in admission'), ('discrimination', 'Complaints of alleged discrimination of students from SC/ST/OBC/Women/Minority or Disabled categories'), ('scholarship_delay', 'Non payment or delay in payment of scholarships to any student'), ('exam_delay', 'Delay in conduct of examinations or declaration of results'), ('no_student_amenities', 'No provision of student amenities'), ('unfair_evaluation', 'Unfair evaluation practices'), ('Other', 'Other')], max_length=100, verbose_name='Nature of Grievance'),
        ),
        migrations.AlterField(
            model_name='historicalgrievance',
            name='complainant_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('non_teaching_staff', 'Non Teaching Staff'), ('Other', 'Other')], max_length=50, verbose_name='Complainant'),
        ),
        migrations.AlterField(
            model_name='historicalgrievance',
            name='nature_of_grievance',
            field=models.CharField(choices=[('admission_contrary_to_merit', 'Making admission contrary to merit'), ('irregularity_in_admission', 'Irregularity in the admission process'), ('refusing_admission', 'Refusing admission in accordance with the declared admission policy of the institute'), ('non_publication_of_prospectus', 'Non publication of prospectus'), ('false_misleading_prospectus', 'Publishing false or misleading information in the prospectus'), ('withhold_documents', 'Withhold or refuse to return any document (certificates/degree/diploma or any other award/document for the purpose of seeking admission)'), ('excess_fee_demand', 'Demand of money in excess of that specified in the declared admission policy'), ('reservation_policy_breach', 'Breach of the policy for reservation in admission'), ('discrimination', 'Complaints of alleged discrimination of students from SC/ST/OBC/Women/Minority or Disabled categories'), ('scholarship_delay', 'Non payment or delay in payment of scholarships to any student'), ('exam_delay', 'Delay in conduct of examinations or declaration of results'), ('no_student_amenities', 'No provision of student amenities'), ('unfair_evaluation', 'Unfair evaluation practices'), ('Other', 'Other')], max_length=100, verbose_name='Nature of Grievance'),
        ),
    ]
