# Generated by Django 5.0.1 on 2026-08-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_alter_grievance_complainant_type_and_more'),
        ('portals', '0004_update_grievance_other_choices'),
    ]

    operations = [
    ]
