# Generated by Django 5.0.1 on 2026-08-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_rename_other_complainant_type_grievance_others_complainant_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discriminationattachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='feedbackattachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='grievanceattachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='grievancesignature',
            options={'verbose_name': 'Signature', 'verbose_name_plural': 'Signatures'},
        ),
        migrations.AlterModelOptions(
            name='iccsignature',
            options={'verbose_name': 'Signature', 'verbose_name_plural': 'Signatures'},
        ),
        migrations.AlterField(
            model_name='discriminationcomplaint',
            name='category_belonging',
            field=models.CharField(choices=[('sc_st', 'SC/ST'), ('obc', 'OBC'), ('disable', 'Disable (PwD)'), ('minority', 'Minority'), ('Other', 'Other')], max_length=50, verbose_name='Category you belong'),
        ),
        migrations.AlterField(
            model_name='discriminationcomplaint',
            name='complaint_discrimination',
            field=models.CharField(choices=[('sc_st', 'SC/ST'), ('obc', 'OBC'), ('disable', 'Disable (PwD)'), ('minority', 'Minority'), ('Other', 'Other')], max_length=50, verbose_name='Complaint Discrimination'),
        ),
        migrations.AlterField(
            model_name='historicaldiscriminationcomplaint',
            name='category_belonging',
            field=models.CharField(choices=[('sc_st', 'SC/ST'), ('obc', 'OBC'), ('disable', 'Disable (PwD)'), ('minority', 'Minority'), ('Other', 'Other')], max_length=50, verbose_name='Category you belong'),
        ),
        migrations.AlterField(
            model_name='historicaldiscriminationcomplaint',
            name='complaint_discrimination',
            field=models.CharField(choices=[('sc_st', 'SC/ST'), ('obc', 'OBC'), ('disable', 'Disable (PwD)'), ('minority', 'Minority'), ('Other', 'Other')], max_length=50, verbose_name='Complaint Discrimination'),
        ),
        migrations.AlterField(
            model_name='historicalicccomplaint',
            name='nature_of_grievance',
            field=models.CharField(choices=[('sexual_harassment', 'Sexual Harassment'), ('workplace_bullying', 'Workplace Bullying'), ('discrimination', 'Discrimination'), ('Other', 'Other')], max_length=100, verbose_name='Nature of Grievance'),
        ),
        migrations.AlterField(
            model_name='historicalstudentfeedback',
            name='course_name',
            field=models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('phd', 'Ph.D.'), ('diploma', 'Diploma'), ('Other', 'Other')], max_length=100, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='historicalstudentfeedback',
            name='subject_of_feedback',
            field=models.CharField(choices=[('academic', 'Academic'), ('infrastructure', 'Infrastructure'), ('hostel', 'Hostel'), ('extracurricular', 'Extracurricular Activities'), ('administration', 'Administration'), ('Other', 'Other')], max_length=100, verbose_name='Subject of your Feedback'),
        ),
        migrations.AlterField(
            model_name='icccomplaint',
            name='nature_of_grievance',
            field=models.CharField(choices=[('sexual_harassment', 'Sexual Harassment'), ('workplace_bullying', 'Workplace Bullying'), ('discrimination', 'Discrimination'), ('Other', 'Other')], max_length=100, verbose_name='Nature of Grievance'),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='course_name',
            field=models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('phd', 'Ph.D.'), ('diploma', 'Diploma'), ('Other', 'Other')], max_length=100, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='subject_of_feedback',
            field=models.CharField(choices=[('academic', 'Academic'), ('infrastructure', 'Infrastructure'), ('hostel', 'Hostel'), ('extracurricular', 'Extracurricular Activities'), ('administration', 'Administration'), ('Other', 'Other')], max_length=100, verbose_name='Subject of your Feedback'),
        ),
    ]
