# Generated by Django 5.0.1 on 2026-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_alter_discriminationattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discriminationcomplaint',
            name='others_complaint_discrimination',
            field=models.CharField(blank=True, help_text="Required if Complaint Discrimination is 'Other'", max_length=255, null=True, verbose_name='Specify Other Complaint Discrimination'),
        ),
        migrations.AddField(
            model_name='historicaldiscriminationcomplaint',
            name='others_complaint_discrimination',
            field=models.CharField(blank=True, help_text="Required if Complaint Discrimination is 'Other'", max_length=255, null=True, verbose_name='Specify Other Complaint Discrimination'),
        ),
        migrations.AddField(
            model_name='historicalstudentfeedback',
            name='others_subject_of_feedback',
            field=models.CharField(blank=True, help_text="Required if Subject of Feedback is 'Other'", max_length=255, null=True, verbose_name='Specify Other Subject of Feedback'),
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='others_subject_of_feedback',
            field=models.CharField(blank=True, help_text="Required if Subject of Feedback is 'Other'", max_length=255, null=True, verbose_name='Specify Other Subject of Feedback'),
        ),
    ]
