# Generated by Django 5.0.1 on 2026-08-25 10:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0008_discriminationcomplaint_others_complaint_discrimination_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiRaggingAffidavit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('student_name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('enrollment_number', models.CharField(max_length=100, verbose_name='Enrollment / Roll No.')),
                ('course_name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('student_phone', models.CharField(max_length=15, verbose_name='Student Phone')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('parent_name', models.CharField(max_length=255, verbose_name='Parent/Guardian Name')),
                ('parent_phone', models.CharField(max_length=15, verbose_name='Parent/Guardian Phone')),
                ('student_affidavit', models.FileField(upload_to='anti_ragging_affidavits/student/%Y/%m/', verbose_name='Student Affidavit PDF')),
                ('parent_affidavit', models.FileField(upload_to='anti_ragging_affidavits/parent/%Y/%m/', verbose_name='Parent Affidavit PDF')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anti-Ragging Affidavit',
                'verbose_name_plural': 'Anti-Ragging Affidavits',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AntiRaggingCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('committee', 'Anti-Ragging Committee'), ('squad', 'Anti-Ragging Squad')], max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Anti-Ragging Committee Member',
                'verbose_name_plural': 'Anti-Ragging Committee Members',
                'ordering': ['role', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AntiRaggingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('regulation', 'UGC Regulation'), ('policy', 'University Policy'), ('report', 'Annual Compliance Report'), ('hostel_safety', 'Hostel Safety Guideline'), ('affidavit', 'Affidavit Format')], max_length=50)),
                ('file', models.FileField(upload_to='anti_ragging/documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anti-Ragging Document',
                'verbose_name_plural': 'Anti-Ragging Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AntiRaggingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Anti-Ragging FAQ',
                'verbose_name_plural': 'Anti-Ragging FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AntiRaggingHelpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='e.g., "National Helpline"', max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Anti-Ragging Helpline',
                'verbose_name_plural': 'Anti-Ragging Helplines',
                'ordering': ['-is_emergency', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AntiRaggingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('poster', 'Poster'), ('brochure', 'Brochure'), ('video', 'Video Link')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='anti_ragging/materials/%Y/%m/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anti-Ragging Material',
                'verbose_name_plural': 'Anti-Ragging Materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAntiRaggingAffidavit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('student_name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('enrollment_number', models.CharField(max_length=100, verbose_name='Enrollment / Roll No.')),
                ('course_name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('student_phone', models.CharField(max_length=15, verbose_name='Student Phone')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('parent_name', models.CharField(max_length=255, verbose_name='Parent/Guardian Name')),
                ('parent_phone', models.CharField(max_length=15, verbose_name='Parent/Guardian Phone')),
                ('student_affidavit', models.TextField(max_length=100, verbose_name='Student Affidavit PDF')),
                ('parent_affidavit', models.TextField(max_length=100, verbose_name='Parent Affidavit PDF')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Anti-Ragging Affidavit',
                'verbose_name_plural': 'historical Anti-Ragging Affidavits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
