# Generated by Django 5.0.1 on 2026-09-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0009_antiraggingaffidavit_antiraggingcommitteemember_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AntiRaggingAffidavit',
        ),
        migrations.DeleteModel(
            name='AntiRaggingCommitteeMember',
        ),
        migrations.DeleteModel(
            name='AntiRaggingDocument',
        ),
        migrations.DeleteModel(
            name='AntiRaggingFAQ',
        ),
        migrations.DeleteModel(
            name='AntiRaggingHelpline',
        ),
        migrations.DeleteModel(
            name='AntiRaggingMaterial',
        ),
        migrations.DeleteModel(
            name='HistoricalAntiRaggingAffidavit',
        ),
    ]
