# Generated by Django 5.0.1 on 2026-04-15 08:59

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0029_remove_researchscholar_co_supervisor_and_more'),
        ('faculty', '0018_alter_faculty_research_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('patent_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Filed', 'Filed'), ('Published', 'Published'), ('Granted', 'Granted')], default='Filed', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='academics.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_year', models.PositiveIntegerField()),
                ('doi_url', models.URLField(blank=True, max_length=500, null=True)),
                ('publication_type', models.CharField(choices=[('Journal', 'Journal Paper'), ('Conference', 'Conference Paper'), ('Book', 'Book'), ('Book Chapter', 'Book Chapter'), ('Patent', 'Patent'), ('Others', 'Others')], default='Journal', max_length=50)),
                ('citation', models.TextField(blank=True, help_text='Full citation string if available')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='academics.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='faculty.faculty')),
            ],
            options={
                'ordering': ['-publication_year'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_areas', to='academics.department')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDevelopmentCellMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Designation in R&D Cell e.g. Director, Member', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_cell_roles', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'R&D Cell Member',
                'verbose_name_plural': 'R&D Cell Members',
                'ordering': ['order', 'faculty__name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='research/facilities/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_facilities', to='faculty.faculty')),
            ],
            options={
                'verbose_name_plural': 'Research Facilities',
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('funding_agency', models.CharField(max_length=255)),
                ('amount_sanctioned', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('co_investigators', models.ManyToManyField(blank=True, related_name='co_pi_projects_new', to='faculty.faculty')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects_new', to='academics.department')),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_projects_new', to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchScholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_name', models.CharField(max_length=255)),
                ('enrollment_no', models.CharField(max_length=100, unique=True)),
                ('research_topic', models.CharField(max_length=500)),
                ('registration_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pursuing', 'Pursuing'), ('Thesis Submitted', 'Thesis Submitted'), ('Awarded', 'Awarded')], default='Pursuing', max_length=20)),
                ('co_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_supervised_scholars_new', to='faculty.faculty')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholars_new', to='academics.department')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_scholars_new', to='faculty.faculty')),
            ],
        ),
    ]
