# Generated by Django 5.0.1 on 2026-04-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_alter_faculty_research_exp'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchscholar',
            name='registration_year',
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='award_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='date_of_registration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='thesis_submission_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='viva_voce_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('Journal', 'Journal Paper'), ('Conference', 'Conference Paper'), ('Book', 'Book'), ('Book Chapter', 'Book Chapter'), ('Patent', 'Patent'), ('Others', 'Others')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='researchscholar',
            name='co_supervisor',
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='enrollment_no',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='research_topic',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='co_supervisor',
            field=models.ManyToManyField(blank=True, related_name='co_supervised_scholars_new', to='faculty.faculty'),
        ),
    ]
