# Generated by Django 5.0.1 on 2026-04-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_remove_researchscholar_registration_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchscholar',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
