# Generated by Django 5.0.1 on 2026-04-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_alter_faculty_research_exp'),
        ('research', '0003_researchscholar_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchscholar',
            name='co_supervisor',
            field=models.ManyToManyField(blank=True, help_text='Select multiple time to add many co-supervisor(s)', related_name='co_supervised_scholars_new', to='faculty.faculty'),
        ),
    ]
