# Generated by Django 5.0.1 on 2026-04-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_alter_faculty_research_exp'),
        ('research', '0004_alter_researchscholar_co_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='others_funding_agency',
            field=models.CharField(blank=True, help_text="Please specify funding agency name if 'Others' is selected", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='co_investigators',
            field=models.ManyToManyField(blank=True, help_text='Select multiple time to add many co-investigator(s)', related_name='co_pi_projects_new', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='funding_agency',
            field=models.CharField(choices=[('DST', 'DST'), ('UGC', 'UGC'), ('DRDO', 'DRDO'), ('ICMR', 'ICMR'), ('ISRO', 'ISRO'), ('NHRC', 'NHRC'), ('ICSSR', 'ICSSR'), ('Others', 'Others')], max_length=20),
        ),
    ]
