# Generated by Django 5.0.1 on 2026-04-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_researchproject_others_funding_agency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-publication_date']},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='journal_name',
            new_name='name_of_journal_or_conference_or_publisher',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='publication',
            name='indexing',
            field=models.CharField(choices=[('Scopus', 'Scopus'), ('Web of Science', 'Web of Science'), ('SJR', 'SJR'), ('Scimago', 'Scimago'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='others_indexing',
            field=models.CharField(blank=True, help_text="Please specify indexing name if 'Others' is selected", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('Journal', 'Journal Paper'), ('Conference', 'Conference Paper'), ('Book', 'Book'), ('Book Chapter', 'Book Chapter'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='others_funding_agency',
            field=models.CharField(blank=True, help_text="Please specify funding agency name if 'Others' is selected", max_length=100, null=True),
        ),
    ]
