# Generated by Django 5.0.1 on 2026-04-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcharea',
            old_name='name',
            new_name='available_research_areas_or_Specialization',
        ),
        migrations.AlterField(
            model_name='publication',
            name='indexing',
            field=models.CharField(blank=True, choices=[('Scopus', 'Scopus'), ('Web of Science', 'Web of Science'), ('SJR', 'SJR'), ('Scimago', 'Scimago'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('Journal', 'Journal Paper'), ('Conference', 'Conference Paper'), ('Book', 'Book'), ('Book Chapter', 'Book Chapter'), ('Others', 'Others')], max_length=50),
        ),
    ]
