# Generated by Django 5.0.1 on 2026-04-21 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_remove_researchscholar_co_supervisor_and_more'),
        ('research', '0007_rename_name_researcharea_available_research_areas_or_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='year',
        ),
        migrations.RemoveField(
            model_name='researchfacility',
            name='location',
        ),
        migrations.AddField(
            model_name='patent',
            name='date_of_filing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='academics.department'),
        ),
    ]
