# Generated by Django 5.0.1 on 2026-04-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_remove_researchscholar_co_supervisor_and_more'),
        ('research', '0008_remove_patent_year_remove_researchfacility_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='academics.department'),
        ),
    ]
