# Generated by Django 5.0.1 on 2026-04-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_alter_faculty_research_exp'),
        ('research', '0009_alter_publication_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='faculty.faculty'),
        ),
    ]
