# Generated by Django 5.0.1 on 2026-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_alter_publication_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchscholar',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('Journal Paper', 'Journal Paper'), ('Conference Paper', 'Conference Paper'), ('Research Paper', 'Research Paper'), ('Book', 'Book'), ('Book Chapter', 'Book Chapter'), ('Others', 'Others')], max_length=50),
        ),
    ]
