# Generated by Django 5.0.1 on 2026-04-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_researchscholar_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchscholar',
            name='award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='research_topic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='thesis_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='viva_voce_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
