# Generated by Django 5.0.1 on 2026-04-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_alter_researchscholar_award_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchscholar',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
