# Generated by Django 5.0.1 on 2026-04-22 10:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0020_alter_faculty_bio_alter_faculty_google_scholar_url_and_more'),
        ('research', '0013_alter_researchscholar_date_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('Journal Paper', 'Journal Paper'), ('Conference Paper', 'Conference Paper'), ('Research Paper', 'Research Paper'), ('Book', 'Book'), ('Book Chapter', 'Book Chapter'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchfacility',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='principal_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_projects_new', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_scholars_new', to='faculty.faculty'),
        ),
    ]
