# Generated by Django 5.0.1 on 2026-04-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_alter_patent_description_alter_patent_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50),
        ),
        migrations.AddField(
            model_name='researchfacility',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50),
        ),
    ]
