# Generated by Django 5.0.1 on 2026-04-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_department_campus'),
        ('faculty', '0020_alter_faculty_bio_alter_faculty_google_scholar_url_and_more'),
        ('research', '0015_patent_campus_publication_campus_researcharea_campus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_consultancy', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_awarding_agency_organization', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_sanctioned', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('campus', models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], default='BBAU', max_length=50)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultancies', to='academics.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultancies', to='faculty.faculty')),
            ],
        ),
    ]
