# Generated by Django 5.0.1 on 2026-04-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_consultancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultancy',
            options={'verbose_name_plural': 'Consultancies'},
        ),
    ]
