# Generated by Django 5.0.1 on 2026-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_consultancy_publish_status_patent_publish_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to R&D Cell'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected by R&D Cell')], default='PUBLISHED', help_text='Controls visibility on the public website.', max_length=15),
        ),
        migrations.AlterField(
            model_name='patent',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to R&D Cell'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected by R&D Cell')], default='PUBLISHED', help_text='Controls visibility on the public website.', max_length=15),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to R&D Cell'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected by R&D Cell')], default='PUBLISHED', help_text='Controls visibility on the public website.', max_length=15),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to R&D Cell'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected by R&D Cell')], default='PUBLISHED', help_text='Controls visibility on the public website.', max_length=15),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to R&D Cell'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected by R&D Cell')], default='PUBLISHED', help_text='Controls visibility on the public website.', max_length=15),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to R&D Cell'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected by R&D Cell')], default='PUBLISHED', help_text='Controls visibility on the public website.', max_length=15),
        ),
    ]
