# Generated by Django 5.0.1 on 2026-04-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0019_alter_consultancy_publish_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='publish_status',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='publish_status',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publish_status',
        ),
        migrations.RemoveField(
            model_name='researcharea',
            name='publish_status',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='publish_status',
        ),
        migrations.RemoveField(
            model_name='researchscholar',
            name='publish_status',
        ),
    ]
