# Generated by Django 5.0.1 on 2026-04-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0020_remove_consultancy_publish_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultancy',
            old_name='amount_sanctioned',
            new_name='amount',
        ),
    ]
