# Generated by Django 5.0.1 on 2026-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0021_rename_amount_sanctioned_consultancy_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='other_publication_type',
            field=models.CharField(blank=True, help_text="Please specify publication type if 'Others' is selected", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('Journal Paper', 'Journal Paper'), ('Conference Paper', 'Conference Paper'), ('Book', 'Book'), ('Book Chapter', 'Book Chapter'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
