# Generated by Django 5.0.1 on 2026-04-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0022_publication_other_publication_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchscholar',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('EWS', 'EWS'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='other_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
