# Generated by Django 5.0.1 on 2026-04-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0023_researchscholar_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchscholar',
            name='other_gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
