# Generated by Django 5.0.1 on 2026-04-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0024_researchscholar_other_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchscholar',
            name='other_gender',
            field=models.CharField(blank=True, help_text="Please specify gender if 'Other' is selected", max_length=50, null=True),
        ),
    ]
