# Generated by Django 5.0.1 on 2026-04-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0026_consultancy_deleted_at_consultancy_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patent',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], max_length=50),
        ),
    ]
