# Generated by Django 5.0.1 on 2026-04-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0027_alter_consultancy_campus_alter_patent_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcharea',
            name='campus',
            field=models.CharField(choices=[('BBAU', 'BBAU'), ('Satellite Campus Amethi', 'Satellite Campus Amethi')], max_length=50),
        ),
    ]
