# Generated by Django 5.0.1 on 2026-05-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0029_historicalconsultancy_historicalpatent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatent',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='campus',
        ),
        migrations.AlterField(
            model_name='historicalresearchscholar',
            name='research_topic',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Research Topic /Title'),
        ),
        migrations.AlterField(
            model_name='historicalresearchscholar',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresearchscholar',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='research_topic',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Research Topic /Title'),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialization'),
        ),
    ]
