# Generated by Django 5.0.1 on 2026-06-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_alter_course_course_code_and_more'),
        ('faculty', '0038_alter_faculty_orcid_id_and_more'),
        ('research', '0030_remove_historicalpatent_campus_remove_patent_campus_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='researchscholar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('scholar_name', 'department', 'supervisor', 'date_of_birth'), name='unique_scholar_dept_supervisor_dob'),
        ),
    ]
