# Generated by Django 5.0.1 on 2026-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_alter_course_course_code_and_more'),
        ('faculty', '0038_alter_faculty_orcid_id_and_more'),
        ('research', '0031_add_unique_constraint_research_scholar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consultancy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('faculty', 'nature_of_consultancy', 'start_date', 'department'), name='unique_consultancy_faculty_nature_date_dept'),
        ),
        migrations.AddConstraint(
            model_name='patent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('title', 'faculty', 'department'), name='unique_patent_title_faculty_dept'),
        ),
        migrations.AddConstraint(
            model_name='patent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('patent_number__isnull', False)), fields=('patent_number',), name='unique_patent_number'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('title', 'faculty', 'department'), name='unique_pub_title_faculty_dept'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(condition=models.Q(('doi_url__isnull', False), ('is_deleted', False)), fields=('doi_url',), name='unique_pub_doi_url'),
        ),
        migrations.AddConstraint(
            model_name='researchproject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('title', 'principal_investigator', 'department'), name='unique_project_title_pi_dept'),
        ),
    ]
