# Generated by Django 5.0.1 on 2026-06-23 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0038_alter_faculty_orcid_id_and_more'),
        ('research', '0032_add_multiple_research_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.PositiveIntegerField(default=1)),
                ('author_role', models.CharField(choices=[('Main Inventor', 'Main Inventor'), ('Co-Inventor', 'Co-Inventor')], default='Main Inventor', max_length=50)),
            ],
            options={
                'ordering': ['author_order'],
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.PositiveIntegerField(default=1)),
                ('author_role', models.CharField(choices=[('Main Author', 'Main Author'), ('Co-Author', 'Co-Author'), ('Corresponding Author', 'Corresponding Author')], default='Main Author', max_length=50)),
            ],
            options={
                'ordering': ['author_order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='patent',
            name='unique_patent_title_faculty_dept',
        ),
        migrations.RemoveConstraint(
            model_name='publication',
            name='unique_pub_title_faculty_dept',
        ),
        migrations.RemoveField(
            model_name='historicalpatent',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicalpatent',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='historicalpublication',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicalpublication',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='department',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='faculty',
        ),
        migrations.AddField(
            model_name='historicalpatent',
            name='full_inventor_list',
            field=models.TextField(blank=True, help_text="Exact string of all inventors (e.g. 'J. Doe, M. Smith')", null=True),
        ),
        migrations.AddField(
            model_name='historicalpublication',
            name='full_author_list',
            field=models.TextField(blank=True, help_text="Exact string of all authors (e.g. 'J. Doe, M. Smith')", null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='full_inventor_list',
            field=models.TextField(blank=True, help_text="Exact string of all inventors (e.g. 'J. Doe, M. Smith')", null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='full_author_list',
            field=models.TextField(blank=True, help_text="Exact string of all authors (e.g. 'J. Doe, M. Smith')", null=True),
        ),
        migrations.AddField(
            model_name='patentauthor',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='patentauthor',
            name='patent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.patent'),
        ),
        migrations.AddField(
            model_name='patent',
            name='internal_inventors',
            field=models.ManyToManyField(blank=True, related_name='internal_patents', through='research.PatentAuthor', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='publicationauthor',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='publicationauthor',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='internal_authors',
            field=models.ManyToManyField(blank=True, related_name='internal_publications', through='research.PublicationAuthor', to='faculty.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='patentauthor',
            unique_together={('patent', 'faculty')},
        ),
        migrations.AlterUniqueTogether(
            name='publicationauthor',
            unique_together={('publication', 'faculty')},
        ),
    ]
