# Generated by Django 5.0.1 on 2026-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0033_update_research_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationauthor',
            name='author_role',
            field=models.CharField(choices=[('Main Author', 'Main Author'), ('Co-Author', 'Co-Author')], default='Main Author', max_length=50),
        ),
    ]
