# Generated by Django 5.0.1 on 2026-06-25 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0034_alter_publicationauthor_author_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresearchscholar',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='historicalresearchscholar',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpublication',
            name='full_author_list',
            field=models.TextField(blank=True, help_text='Enter the list of all the author separated by commas ', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='full_author_list',
            field=models.TextField(blank=True, help_text='Enter the list of all the author separated by commas ', null=True),
        ),
    ]
