# Generated by Django 5.0.1 on 2026-07-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0035_historicalresearchscholar_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublication',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(),
        ),
    ]
