# Generated by Django 5.0.1 on 2026-07-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0036_publication_title_non_nullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchscholar',
            old_name='subject',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='historicalresearchscholar',
            old_name='subject',
            new_name='specialization',
        ),
    ]
