# Generated by Django 5.0.1 on 2026-07-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0039_alter_faculty_orcid_id_and_more'),
        ('research', '0037_rename_subject_to_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='principal_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_projects_new', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_scholars_new', to='faculty.faculty'),
        ),
    ]
