# Generated by Django 5.0.1 on 2026-07-03 12:04

import apps.research.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0038_fix_on_delete_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublication',
            name='doi_url',
            field=models.CharField(blank=True, help_text="Enter DOI as '10.XXXX/suffix' or 'https://doi.org/10.XXXX/suffix'.", max_length=500, null=True, validators=[apps.research.models.validate_doi]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi_url',
            field=models.CharField(blank=True, help_text="Enter DOI as '10.XXXX/suffix' or 'https://doi.org/10.XXXX/suffix'.", max_length=500, null=True, validators=[apps.research.models.validate_doi]),
        ),
    ]
