# Generated by Django 5.0.1 on 2026-07-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0039_doi_url_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatent',
            name='title_fp',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated alphanumeric fingerprint of the title for duplicate detection.', max_length=1000),
        ),
        migrations.AddField(
            model_name='historicalpublication',
            name='title_fp',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated alphanumeric fingerprint of the title for duplicate detection.', max_length=1000),
        ),
        migrations.AddField(
            model_name='patent',
            name='title_fp',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated alphanumeric fingerprint of the title for duplicate detection.', max_length=1000),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_fp',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated alphanumeric fingerprint of the title for duplicate detection.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalpatent',
            name='full_inventor_list',
            field=models.TextField(blank=True, help_text='Exact string of all inventors seperated by commas if they are form other institutions', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpublication',
            name='full_author_list',
            field=models.TextField(blank=True, help_text='Enter the list of all the author separated by commas if they are form other institutions', null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='full_inventor_list',
            field=models.TextField(blank=True, help_text='Exact string of all inventors seperated by commas if they are form other institutions', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='full_author_list',
            field=models.TextField(blank=True, help_text='Enter the list of all the author separated by commas if they are form other institutions', null=True),
        ),
    ]
