# Generated by Django 5.0.1 on 2026-07-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0040_add_title_fp_index_to_publication_patent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patent',
            options={'ordering': ['-date_of_filing']},
        ),
        migrations.AlterModelOptions(
            name='researchscholar',
            options={'ordering': ['-date_of_registration']},
        ),
    ]
