# Generated by Django 5.0.1 on 2026-08-17 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0040_add_other_material_type_and_orcid_validator'),
        ('research', '0041_alter_patent_options_alter_researchscholar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresearchdevelopmentcellmember',
            name='faculty',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faculty.faculty', verbose_name='R&D Cell Member'),
        ),
        migrations.AlterField(
            model_name='researchdevelopmentcellmember',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_cell_roles', to='faculty.faculty', verbose_name='R&D Cell Member'),
        ),
    ]
