# Generated by Django 5.0.1 on 2026-09-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0042_alter_historicalresearchdevelopmentcellmember_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatent',
            name='full_inventor_list',
            field=models.TextField(blank=True, help_text='Name of all inventors seperated by commas if they are form other institutions', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpublication',
            name='full_author_list',
            field=models.TextField(blank=True, help_text='List of all the author separated by commas if they are from other institutions or scholars', null=True),
        ),
        migrations.AlterField(
            model_name='historicalresearchscholar',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='full_inventor_list',
            field=models.TextField(blank=True, help_text='Name of all inventors seperated by commas if they are form other institutions', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='full_author_list',
            field=models.TextField(blank=True, help_text='List of all the author separated by commas if they are from other institutions or scholars', null=True),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
