name: Deploy to PRODUCTION

on:
  push:
    branches:
      - live

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, django, backend]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Django PRODUCTION
        run: |
          rsync -av --delete  --exclude='.env*' --exclude='media/' --exclude='staticfiles/' --exclude='.git' ./ /srv/apps/django/
          cd /srv/apps/django
          chmod +x deploy-live.sh
          ./deploy-live.sh
