name: Deploy to DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, django, backend]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Django DEV
        run: |
          rsync -av --delete  --exclude='.env*' --exclude='media/' --exclude='staticfiles/' --exclude='.git' ./ /srv/apps/django/dev/
          cd /srv/apps/django/dev
          chmod +x deploy-dev.sh
          ./deploy-dev.sh
